---
################################# 1Password setup #################################################################
# 1Password connector installation
# Prerequisits for 1password integration and running of these tasks:
# 1. 1Password integration: https://docs.hpi-schul-cloud.org/pages/viewpage.action?pageId=154189180#id-1PasswordConnector/Operator-Creatinganintegration
# 2. Local environment setup: https://docs.hpi-schul-cloud.org/display/PROD/Ansible+Working+with+Helm+Charts#AnsibleWorkingwithHelmCharts-Preparation
# 3. Execute make requirements
# See https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_repository_module.html
- name: Add 1password chart repo
  kubernetes.core.helm_repository:
    name: 1password
    repo_url: "https://1password.github.io/connect-helm-charts"
  check_mode: false
  changed_when: false

# The onepassword credentials json file is used by the connector to connect to central 1password service
# See https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
- name: Create onepassword credentials secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ onepassword_connector_credentials_name }}"
        namespace: default
      data:
        1password-credentials.json: "{{ onepassword_connector_credentials_json | b64encode | b64encode}}"

# The onepassword token is used by the operator to retrieve the secrets from the connector
# See https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
- name: Create onepassword servicecenter token secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ onepassword_connector_token_name }}"
        namespace: default
      data:
        token: "{{ onepassword_connector_token_value | b64encode}}"
  when: stage not in ["prod", "staging"] or "schulcloud" not in group_names

# This clusterrolebinding is used in the dev environment to grant access for the 1password operator to all namespaces
# See https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
- name: Create onepassword ClusterRoleBinding
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: onepassword-connect-operator-default
      subjects:
        - kind: ServiceAccount
          name: onepassword-connect-operator
          namespace: default
      roleRef:
        kind: ClusterRole
        name: onepassword-connect-operator
        apiGroup: rbac.authorization.k8s.io
  when: stage not in ["prod", "staging"] or "schulcloud" not in group_names

# See https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
- name: Install 1password connector and operator
  kubernetes.core.helm:
    name: onepassword
    chart_ref: 1password/connect
    chart_version: "{{ onepassword_connector_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: default
    values:
      "{{ onepassword_connector_values }}"
