# Setup Cloudprober
# Create Namespace
- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    api_version: v1
    name: "{{ cloudprober_namespace }}"
    kind: Namespace
  tags: cloudprober

# Create ConfigMap to store configuration
- name: Create Cloudprober configmap
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ cloudprober_configmap }}"
        namespace: "{{ cloudprober_namespace }}"
      data:
        cloudprober.cfg: |-
          surfacer {
            type: PROMETHEUS

            prometheus_surfacer {
              # Following option adds a prefix to exported metrics, for example,
              # "total" metric is exported as "cloudprober_total".
              metrics_prefix: "cloudprober_"
            }
          }
          probe {
            name: "HTTP_Probe"
            type: HTTP
            targets {
              host_names: "{{ fluentbit_target_host }}, {{ vmagent_ingress_host }}"
            }
          }
          probe {
            name: "Fluentbit pods"
            type: PING
            targets {
              k8s {
                namespace: "kube-system"
                pods: "fluent.*"
              }
            }
            ping_probe {
              use_datagram_socket: false
            }
          }
          probe {
            name: "coredns pods"
            type: PING
            targets {
              k8s {
                namespace: "kube-system"
                pods: "coredns.*"
              }
            }
            ping_probe {
              use_datagram_socket: false
            }
          }
          probe {
            name: "csi pods"
            type: PING
            targets {
              k8s {
                namespace: "kube-system"
                pods: "csi.*"
              }
            }
            ping_probe {
              use_datagram_socket: false
            }
          }
          probe {
            name: "PING_Monitoring"
            type: PING
            targets {
              k8s {
                namespace: "monitoring"
                pods: ".*"
              }
            }
            ping_probe {
              use_datagram_socket: false
            }
          }
          probe {
            name: "Ingress_Probe"
            type: HTTP
            targets {
              k8s {
                namespace: "infra-dbildungscloud-01"
                ingresses: ".*"
              }
            }
          }          
          probe {
            name: "Services"
            type: TCP
            targets {
              k8s {
                namespace: "infra-dbildungscloud-01"
                services: ".*"
              }
            }
          }
          probe {
            name: "K8S_Api"
            type: HTTPS
            targets {
              k8s {
                namespace: "default"
                services: "kubernetes"
              }
            }
          }
          probe {
            name: "K8S_Controlplane"
            type: TCP
            targets {
              k8s {
                namespace: "default"
                endpoints: "kubernetes"
              }
            }
          }
  tags: cloudprober
        
        
# Create Secret to store tokens and access data required
- name: Create Cloudprober secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: onepassword.com/v1
      kind: OnePasswordItem
      metadata:
        name: "{{ cloudprober_secret }}"
        namespace: "{{ cloudprober_namespace }}"
      spec:
        itemPath: "vaults/{{ vault }}/items/cloudprober"
  tags: cloudprober

# add helm chart location
- name: Add Cloudprober chart repo
  kubernetes.core.helm_repository:
    name: cloudprober
    repo_url: "https://helm.cloudprober.org"
  check_mode: false
  changed_when: false
  tags: cloudprober

# execute helm chart with values
- name: Install Cloudprober
  kubernetes.core.helm:
    name: cloudprober
    chart_ref: cloudprober/cloudprober
    update_repo_cache: true
    chart_version: "{{ cloudprober_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: "{{ cloudprober_namespace }}"
    wait: true
    values:
      "{{ cloudprober_values }}"
  tags: cloudprober