---
- name: Add clamav user to designated group  
  become: true
  user:
    name: "{{ clamav_username }}" 
    uid: "{{ clamav_useruid }}"
    groups: "{{ clamav_user_group }}"
    append: yes
  when: clamav_enable_auto_scan

- name: Run ClamAV Scan Container 
  become: true
  docker_container:
    name: "{{ clamav_container_name }}"
    image: "{{ clamav_image }}"
    state: started
    restart_policy: unless-stopped 
    volumes: 
      - "{{ clamav_scan_directory + ':/scanned:rw' if clamav_scan_directory is defined else omit }}"
      - "{{ clamav_log_path + ':/var/log/clamav:rw' if clamav_log_path is defined else omit }}"
    entrypoint: "/init-unprivileged"
    user: "{{ clamav_useruid }}"
    ports: 
      - "{{ clamav_port }}"
  when: clamav_enable_auto_scan
