---
- name: Create ClamAV Cron Scan Exclude Options
  set_fact:
    clamav_scan_exclude_options: "{{ clamav_scan_exclude_directories | map('regex_replace', '(.*)', '--exclude-dir=\\1') | join(' ') }}"

- name: Schedule Daily ClamAV Scan 
  become: true 
  cron: 
    name: "Daily ClamAV Scan" 
    job: >
      docker exec {{ clamav_container_name }} clamscan -r --move=/quarantine {{ clamav_scan_exclude_options }} /scanned 2>&1 | tee -a {{ clamav_log_path }}/clamav_scan.log
    cron_file: clamav_scan_schedule 
    state: "{{ 'present' if clamav_enable_auto_scan else 'absent' }}" 
    minute: "32"  
    hour: "*"    
    day: "*"     
    month: "*"   
    weekday: "*" 
    user: clamav
  when: clamav_enable_auto_scan 
