---
- name: Create ClamAV configuration directory
  file:
    path: "/etc/clamav"
    state: directory
    owner: clamav
    group: clamav
    mode: "0755"
  become: true

- name: Create ClamAV configuration directory
  file:
    path: "/var/log/clamav"
    state: directory
    owner: clamav
    group: clamav
    mode: "0755"
  become: true

- name: Create uWSGI and privacyidea log files
  file:
    path: "/var/log/clamav/freshclam.log"
    state: touch
    owner: clamav
    group: clamav
    mode: '0664'
  become: true

# This directory will store the ClamAV virus definition database files

- name: Create ClamAV database directory
  become: true
  file:
    path: "{{ clamav_db_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755


- name: Create ClamAV quarantine directory
  become: true
  file:
    path: "{{ clamav_quarantine_path }}" # Infizierte Dateien werden hier gespeichert
    state: directory
    owner: clamav
    group: clamav
    mode: 0755

- name: Create ClamAV Scan log file
  become: true
  file:
    path: "{{ clamav_scan_log }}" # Infizierte Dateien werden hier gespeichert
    state: directory
    owner: clamav
    group: clamav
    mode: 0755
  

# - name: Configure freshclam
#   become: true
#   template:
#     src: freshclam.conf.j2
#     dest: /etc/clamav/freshclam.conf
#     owner: clamav
#     group: clamav
#     mode: 0755
    
# FreshClam ist ein Tool, das die ClamAV-Datenbank aktualisiert
# freshclam lädt die neuesten Virensignaturen von ClamAV-Servern herunter
# FreshClam ist ein Tool, das die ClamAV-Datenbank aktualisiert
# freshclam lädt die neuesten Virensignaturen von ClamAV-Servern herunter
- name: Run freshclam container to update definitions
  become: true
  docker_container:
    name: "{{ clamav_freshclam_container_name }}"
    image: "{{ clamav_image }}" 
    restart_policy: no # Der Container wird nach dem Update gestoppt und gelöscht
    volumes:
      - "{{ clamav_db_path }}:/data"
    command: freshclam
    detach: false #  Do not run in detached mode. Keep the execution tied to the ansible host
    auto_remove: true # # Clean up and remove the container when finished


  # This task is used for running a prebuild docker image and configure variables
- name: Run ClamAV Scan Container 
  become: true
  docker_container:
    name: "{{ clamav_container_name }}"
    image: "{{ clamav_image }}"
    state: started
    restart_policy: unless-stopped # restart_policy: unless-stopped stellt sicher, dass der Scanner immer läuft, es sei denn, er wird bewusst gestoppt 
    volumes: 
      - "{{ clamav_db_path }}:/data:ro"  # Die ClamAV-Datenbank (/var/clamav-db auf dem Host) wird in den Container gemountet.
      - "{{ clamav_scan_directory }}:/scanned:ro"  # Das Verzeichnis, das gescannt werden soll (/), wird als /scanned in den Container gemountet.
      - "{{ clamav_quarantine_path }}:/quarantine" # Falls ClamAV eine infizierte Datei findet, verschiebt es sie nach /quarantine
    ports: 
      - "3310:3310" # ClamAV kann über Port 3310 Scan-Anfragen erhalten