---
###################### Destroy Nodepools ##########################################################
# Using the Ansible module ionoscloudsdk.ionoscloud.k8s_nodepool to destroy a node pool, it's important
# to note that the module will perform the deletion whether you run it with or without the -C flag.
# To avoid accidental node pool deletions during an Ansible run in check mode, make use of when: not ansible_check_mode.
# See https://docs.ionos.com/ansible/api/managed-kubernetes/k8s_nodepool

- name: Run Terraform
  import_role:
    name: dbildungscloud.infra.resource_pool

- name: Build nodepool list
  set_fact:
    nodepools_to_delete: "{{ terraform_run.outputs.nodepool_zone1_id.value | default([]) + terraform_run.outputs.nodepool_zone2_id.value | default([]) }}"

- name: Debug node pool IDs
  debug:
    var: pool_id
  loop: "{{ nodepools_to_delete }}"
  loop_control:
    loop_var: pool_id
  when: terraform_run.outputs.cluster_id.value is defined

- name: Delete k8s cluster nodepool
  ionoscloudsdk.ionoscloud.k8s_nodepool:
    k8s_cluster_id: "{{ terraform_run.outputs.cluster_id.value }}"
    nodepool_id: "{{ pool_id }}"
    username: "{{ ionos_username | default(omit) }}"
    password: "{{ ionos_password | default(omit) }}"
    token: "{{ ionos_token | default(omit) }}"
    state: absent
  loop: "{{ nodepools_to_delete }}"
  loop_control:
    loop_var: pool_id
  when: not ansible_check_mode and terraform_run.outputs.cluster_id.value is defined
