---
# Namespace cloudprober will be installed Installed in
cloudprober_namespace: "monitoring"

# Name of secret used for Cloudprober access tokens and other "secret" stuff
cloudprober_secret: "cloudprobersecrets"

# Name of config map where cloudprober will look for configuration content must be valid: See https://cloudprober.org/docs/config/latest/overview/
cloudprober_configmap: "cloudproberconfig"

# Version tag for helm chart used
cloudprober_chart_version: 1.13.21

# values.yaml used see https://github.com/cloudprober/helm-charts/blob/main/cloudprober/values.yaml for values
cloudprober_values:
  # extraArgs:
  #   - "--debug_log"
  configMap:
    name: "{{ cloudprober_configmap }}"
    create: false
  envFromSecret: "{{ cloudprober_secret }}"
  securityContext:
    capabilities:
      add: ["NET_RAW"]
    # sysctls:
    #   - name: net.ipv4.ping_group_range
    #     value: "0 5000"