---
  - name: install duply gnupg
    apt:
      name: ['duply','gnupg2','expect']
      update_cache: yes
      state: latest

  - name: Install boto python package
    pip:
      name: boto

  - name: Create backup target configuration files
    include_tasks: backup_target.yml
    tags: [ restore ]
    loop: "{{ schulcloud }}"
    # loop: "{{ groups.sc }}"
    loop_control:
      loop_var: sc_item
    vars:
      backupS3Key: "{{ lookup('dbildungscloud.onepwd.onepwd', vault='sc-prod', secret_name='backup.s3.key', session_shorthand='ansible-run', credentials=op_credentials) }}"
      backupS3Secret: "{{ lookup('dbildungscloud.onepwd.onepwd', vault='sc-prod', secret_name='backup.s3.secret', session_shorthand='ansible-run', credentials=op_credentials) }}"

# Prepares duply profiles and gpg keys for each user in devops and support group 
  - name: Create duply profiles
    include_tasks: duply_configuration.yml
    vars:
      vm_permissions: "{{ user_item.0.permissions.vms | default({}) }}"
    when:
      (user_item.0.name is defined) and
      ((vm_permissions.allhosts | default(false)) or (inventory_hostname in (vm_permissions.hosts | default([])))) and 
      (user_item.1 in ["devops","support"]) # Only devops and support group member are allowed to use gpg keys for support
    loop: "{{ present_users | subelements('permissions.vms.groups', skip_missing=True) }}"
    loop_control:
      loop_var: user_item

  - name: copy duply-restore script
    tags: [ restore ]
    copy:
      src: duply-restore
      dest: "/usr/bin/duply-restore"
      owner: "root"
      group: "root"
      mode: 0755

  - name: copy duply-status script
    tags: [ restore ]
    copy:
      src: duply-status
      dest: "/usr/bin/duply-status"
      owner: "root"
      group: "root"
      mode: 0755
