---
op_session_shorthand: "ansible-run"
tls_auth_certs_dir:
tls_auth_file_permissions:
  # owner:
  # group:
  mode: "0700"
tls_auth_purpose:
tls_auth_vault:
tls_auth_present_clients: []
tls_auth_absent_clients: []
tls_auth_ca_secret_name_base: "{{ tls_auth_purpose }}-ca"
tls_auth_ca_key_secret_name: "{{ tls_auth_ca_secret_name_base }}-key"
tls_auth_ca_cert_secret_name: "{{ tls_auth_ca_secret_name_base }}-cert"
tls_auth_ca_crl_secret_name: "{{ tls_auth_ca_secret_name_base }}-crl"
tls_auth_ca_key_filename: ca.key
tls_auth_ca_key_size: 4096
tls_auth_ca_key_type: RSA
tls_auth_ca_csr_filename: ca.csr
tls_auth_ca_cert_filename: ca.crt
tls_auth_ca_key_basic_constraints:
  - "CA:TRUE"
tls_auth_ca_key_usage:
  - keyCertSign
  - cRLSign
tls_auth_ca_cert_digest: sha256
tls_auth_ca_cert_not_after: "+3650d"
tls_auth_ca_cert_common_name: "{{ tls_auth_purpose }}-ca"
tls_auth_ca_crl_filename: ca.crl
tls_auth_client_secret_base_name: "{{ tls_auth_purpose }}-{{ tls_auth_client }}"
tls_auth_client_key_secret_name: "{{ tls_auth_client_secret_base_name }}-key"
tls_auth_client_cert_secret_name: "{{ tls_auth_client_secret_base_name }}-cert"
tls_auth_client_pkcs12_secret_name: "{{ tls_auth_client_secret_base_name }}-pkcs12"
tls_auth_client_key_filename: "{{ tls_auth_client }}.key"
tls_auth_client_key_size: 4096
tls_auth_client_key_type: RSA
tls_auth_client_csr_filename: "{{ tls_auth_client_csr_filename }}"
tls_auth_client_cert_filename: "{{ tls_auth_client }}.crt"
tls_auth_client_cert_not_after: "+3650d"
tls_auth_client_cert_common_name: "{{ tls_auth_purpose }}-{{ tls_auth_client }}"
tls_auth_client_p12_filename: "{{ tls_auth_client }}.p12"
