---
- name: Check for certificates
  vars:
    domains:
      - "{{ scalelite_basedomain }}"
      - "{{ scalelite_host }}"
      - "{{ scalelite_greenlight_extra_instances | map(attribute='hostname') | list }}"
    files:
      - fullchain.pem
      - privkey.pem
  stat:
    path: "{{ scalelite_letsencrypt_folder }}/live/{{ item }}"
  loop: "{{ domains | flatten | product(files) | map('join', '/') | list }}"
  register: cert_files

- name: Create Letsencrypt certificates
  import_tasks:
    file: initial-certificates.yml
  when: not (cert_files.results | map(attribute='stat.exists') is all)

- name: Ensure the correct permissions
  file:
    state: directory
    recurse: true
    path: "{{ scalelite_letsencrypt_folder }}"
    owner: "{{ scalelite_certbot_user_id }}"
    group: "{{ scalelite_certbot_group_id }}"
    mode: "u=rwX,g=rX,o="
