---
- name: Create Docker logrotate config
  copy:
    content: |
      /var/lib/docker/containers/*/*.log {
        rotate 14
        daily
        compress
        missingok
        delaycompress
        copytruncate
      }
    dest: /etc/logrotate.d/docker
    mode: "0644"

- name: Create Scalelite Nginx logrotate config
  copy:
    content: |
      {{ scalelite_nginx_logs_folder }}/*.log {
        rotate 14
        daily
        compress
        missingok
        delaycompress
        copytruncate
      }
    dest: /etc/logrotate.d/scalelite-nginx
    mode: "0644"
