---
- name: Docker compose down
  community.docker.docker_compose:
    state: absent
    project_src: "{{ scalelite_docker_compose_folder }}"
    remove_orphans: true

- name: Migrate volume content
  copy:
    src: "/var/lib/docker/volumes/{{ scalelite_docker_compose_folder | basename }}_{{ item.name }}-data/_data/"
    dest: "{{ scalelite_docker_volumes_folder }}/{{ item.name }}_data/"
    remote_src: true
    mode: "0700"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - name: postgres
      owner: "{{ scalelite_postgres_user_id }}"
      group: "{{ scalelite_postgres_group_id }}"
    - name: redis
      owner: "{{ scalelite_redis_user_id }}"
      group: "{{ scalelite_redis_group_id }}"

- name: Migrate volume content for extra Greenlight instances
  copy:
    src: "/var/lib/docker/volumes/{{ scalelite_docker_compose_folder | basename }}_redis-{{ item.name }}-data/_data/"
    dest: "{{ scalelite_docker_volumes_folder }}/redis_{{ item.name }}_data/"
    remote_src: true
    mode: "0700"
    owner: "{{ scalelite_redis_user_id }}"
    group: "{{ scalelite_redis_group_id }}"
  loop: "{{ extra_greenlight_instances }}"
