---

- name: Create Grafana PVC
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.name }}-grafana"
        namespace: monitoring
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ prometheus_community_values.grafana.persistence.storageClassName }}"
        resources:
          requests:
            storage: "{{ prometheus_community_values.grafana.persistence.size }}"
  when: item.grafana.enabled
  tags: prometheus
  
- name: Create Kubernetes Secret for Grafana SMTP password
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/runner/.kube/infra-dev-collaboration-01.yaml"
    proxy: "https://proxy.infra-dev-admin-01.dbildungscloud.dev:443"
    proxy_headers: "{{ proxy_headers | default(omit) }}"
    definition:
      apiVersion: onepassword.com/v1
      kind: Secret
      metadata:
        name: grafana-smtp
        namespace: monitoring
      type: Opaque
      stringData:
        smtp_password: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name='grafana-smtp', vault='Infrastructure', field='password', session_shorthand='ansible-run', credentials=op_credentials) }}"
  tags: prometheus

- name: Install Prometheus Stack
  kubernetes.core.helm:
    name: "{{ item.name }}"
    chart_ref: prometheus-community/kube-prometheus-stack
    update_repo_cache: true
    chart_version: "{{ prometheus_community_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: "{{ item.namespace }}"
    wait: true
    wait_timeout: 1200s
    values:
      "{{ prometheus_community_values }}"
  tags: prometheus


