---
- name: Create /data
  file:
    path: "{{ mount_path }}"
    state: directory
    mode: "{{ mount_path_mode }}"

- name: Check whether partition already exists
  parted:
    state: info
    device: "{{ block_device }}"
  register: partition_info

- name: Create Partition if no partition is present
  parted:
    device: "{{ block_device }}"
    number: 1
    part_type: primary
    state: present
    part_start: 0%
    part_end: 100%
  when: partition_info.partitions[0].num is not defined

- name: Make filesystem  
  filesystem:
    fstype: ext4
    dev: "{{ partition_name }}"
  become: true
  when: partition_info.partitions[0].num is not defined

- name: Mount filesystem
  mount:
    state: mounted
    fstype: ext4
    src: "{{ partition_name }}"
    path: "{{ mount_path }}"
    backup: true
  become: true
  when: partition_info.partitions[0].num is not defined
  