
    - name: Install awx-operator
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        template:  awx-operator.yml
      tags:
        - awx

# Normally this PVC is created by the awx-postgres statefulset, but this prevents resizing so we create it beforehand
# The name must be the name that the statefulset uses to create its PVC
    - name: Create AWX Postgres PVC
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: postgres-15-awx-postgres-15-0
            namespace: "{{ awx_namespace }}"
          spec:
            accessModes:
              - "{{ awx_postgres_storage_access_mode }}"
            resources: "{{ awx_postgres_storage_requirements }}"
      tags:
        - awx

    - name: Create AWX PVC
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: "awx-storage"
            namespace: "{{ awx_namespace }}"
          spec:
            accessModes:
              - "ReadWriteMany"
            storageClassName: "nfs-client"
            resources: "{{ awx_web_storage_requirements }}"
      tags:
        - awx

   - name: Install awx
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        definition:
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
            name: awx
            namespace: "{{ awx_namespace }}"
          spec:
            admin_email: "{{ awx_admin_email }}"
            admin_password_secret: "{{ awx_admin_password_secret_name }}"
            ee_resource_requirements: "{{ awx_ee_resource_requirements }}"
            hostname: "{{ awx_hostname }}"
            ingress_type: "{{ awx_ingress_type }}"
            ingress_tls_secret: "{{ awx_ingress_tls_secret_name}}"
            ingress_annotations: "{{ awx_ingress_annotations }}"
            postgres_configuration_secret: "{{ awx_postgres_configuration_secret | default(omit, true) }}"
            postgres_storage_requirements: "{{ awx_postgres_storage_requirements }}"
            postgres_storage_class: "{{ awx_postgres_storage_class }}"
            postgres_resource_requirements: "{{ awx_postgres_resource_requirements }}"
            projects_persistence: "{{ awx_projects_persistence }}"
            # projects_storage_access_mode: "{{ awx_projects_storage_access_mode }}"
            # have not tried this option 
            projects_storage_access_mode: "ReadWriteMany"
            projects_storage_size: "{{ awx_projects_storage_size }}"
            postgres_data_volume_init: true
            secret_key_secret: "{{ awx_secret_key_secret | default(omit, true) }}"
            task_resource_requirements: "{{ awx_task_resource_requirements }}"
            web_resource_requirements: "{{ awx_web_resource_requirements }}"
            projects_existing_claim: "awx-storage"
            projects_storage_class: "nfs-client"
            # security_context_settings:
            #   seLinuxOptions:
            #     level: "s0:c924,c974"
            # init_container_extra_volume_mounts: |
            #   - name: awx-projects
            #     mountPath: /var/lib/awx/projects
            # https://github.com/ansible/awx-operator/issues/931
            # init_container_extra_commands: |
            #   chmod 777 /var/lib/awx/projects/

      tags:
        - awx
