---
- name: Add AWX-Operator Helm repo
  kubernetes.core.helm_repository:
    name: awx-operator
    repo_url: "https://ansible-community.github.io/awx-operator-helm/"
  check_mode: false
  changed_when: false

# Normally this PVC is created by the awx-postgres statefulset, but this prevents resizing so we create it beforehand
# The name must be the name that the statefulset uses to create its PVC
- name: Create AWX Postgres PVC
  kubernetes.core.k8s:
    state: "present"
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ awx_postgres_pvc_name }}"
        namespace: "{{ awx_namespace }}"
      spec:
        accessModes:
          - "{{ awx_postgres_storage_access_mode }}"
        storageClassName: "{{ awx_postgres_storage_class }}"
        resources: "{{ awx_postgres_storage_requirements }}"

- name: Install AWX CRDs
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/{{ terraform_run.outputs.cluster_name.value }}.yaml"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    namespace: "{{ awx_namespace }}"
    # Ansible YAML has issues with '- =' and '- =~' even though they're valid YAML
    resource_definition: "{{ lookup('ansible.builtin.url', item, split_lines=false) | regex_replace('- (=.*)', \"- '\\1'\") }}"
  # When updating the AWX Operator check if there are any new CRDs and add them here
  loop:
    - "https://raw.githubusercontent.com/ansible/awx-operator/refs/tags/{{ awx_operator_version }}/config/crd/bases/awx.ansible.com_awxbackups.yaml"
    - "https://raw.githubusercontent.com/ansible/awx-operator/refs/tags/{{ awx_operator_version }}/config/crd/bases/awx.ansible.com_awxrestores.yaml"
    - "https://raw.githubusercontent.com/ansible/awx-operator/refs/tags/{{ awx_operator_version }}/config/crd/bases/awx.ansible.com_awxs.yaml"
    - "https://raw.githubusercontent.com/ansible/awx-operator/refs/tags/{{ awx_operator_version }}/config/crd/bases/awx.ansible.com_awxmeshingresses.yaml"

- name: Label Kustomize resources so the Helm chart can update them
  vars:
    awx_helm_migration_labels:
      app.kubernetes.io/managed-by: Helm
    awx_helm_migration_annotations:
      meta.helm.sh/release-namespace: "{{ awx_namespace }}"
      meta.helm.sh/release-name: awx
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: "{{ item.apiVersion }}"
      kind: "{{ item.kind }}"
      metadata:
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace | default('') }}"
        labels: "{{ item.metadata.labels | default({}) | combine(awx_helm_migration_labels) }}"
        annotations: "{{ item.metadata.annotations | default({}) | combine(awx_helm_migration_annotations) }}"
  # Split the list of YAML manifests using the separator --- and remove the first item since it is empty
  loop: "{{ (lookup('template', 'awx-operator.yml') | split('---'))[1:] | map('from_yaml') }}"
  loop_control:
    label: "{{ item.metadata.name }}"
  when: awx_operator_migrate_to_helm and item.kind not in ['CustomResourceDefinition', 'Deployment']

- name: Delete old AWX-Operator deployment
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    state: absent
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: awx-operator-controller-manager
        namespace: "{{ awx_namespace }}"
  when: awx_operator_migrate_to_helm

- name: Install AWX-Operator Helm chart
  kubernetes.core.helm:
    name: awx
    chart_ref: awx-operator/awx-operator
    update_repo_cache: true
    chart_version: "{{ awx_operator_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: "{{ awx_namespace }}"
    wait: true
    values:
      "{{ awx_operator_values }}"

- name: Install AWX
  kubernetes.core.k8s:
    state: "present"
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
        namespace: "{{ awx_namespace }}"
      spec: "{{ awx_spec }}"
