
    - name: Install awx-operator
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        template:  "{{ project }}/awx-operator.yml"
      tags:
        - awx

# Normally this PVC is created by the awx-postgres statefulset, but this prevents resizing so we create it beforehand
# The name must be the name that the statefulset uses to create its PVC
    - name: Create AWX Postgres PVC
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: postgres-15-awx-postgres-15-0
            namespace: "{{ awx_namespace }}"
          spec:
            accessModes:
              - "{{ awx_postgres_storage_access_mode }}"
            storageClassName: "{{ awx_postgres_storage_class }}"
            resources: "{{ awx_postgres_storage_requirements }}"
      tags:
        - awx

    - name: Install awx
      kubernetes.core.k8s:
        state: "present"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        definition:
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
            name: awx
            namespace: "{{ awx_namespace }}"
          spec:
            admin_email: "{{ awx_admin_email }}"
            admin_password_secret: "{{ awx_admin_password_secret_name }}"
            secret_key_secret: "{{ awx_secret_key_secret | default(omit, true) }}"
            ingress_type: "{{ awx_ingress_type }}"
            ingress_annotations: "{{ awx_ingress_annotations }}"
            ingress_tls_secret: "{{ awx_ingress_tls_secret_name}}"
            hostname: "{{ awx_hostname }}"
            postgres_configuration_secret: "{{ awx_postgres_configuration_secret | default(omit, true) }}"
            postgres_storage_requirements: "{{ awx_postgres_storage_requirements }}"
            postgres_storage_class: "{{ awx_postgres_storage_class }}"
            postgres_resource_requirements: "{{ awx_postgres_resource_requirements }}"
            web_resource_requirements: "{{ awx_web_resource_requirements }}"
            task_resource_requirements: "{{ awx_task_resource_requirements }}"
            ee_resource_requirements: "{{ awx_ee_resource_requirements }}"
            projects_persistence: "{{ awx_projects_persistence }}"
            projects_storage_access_mode: "{{ awx_projects_storage_access_mode }}"
            projects_storage_size: "{{ awx_projects_storage_size }}"
            postgres_data_volume_init: true
            postgres_init_container_commands: |
              chown 26:0 /var/lib/pgsql/data
              chmod 700 /var/lib/pgsql/data
      tags:
        - awx
