---
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: restart uwsgi
  service:
    name: uwsgi
    state: restarted
    enabled: yes
  become: true

- name: restart sshd
  service: 
    name: sshd
    state: restarted
  
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  become: true