---

- name: restart sshd
  service: 
    name: sshd
    state: restarted
  
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

- name: Reload ha-cluster-exporter
  ansible.builtin.service:
    name: ha-cluster-exporter
    enabled: true
    state: reloaded

- name: reload nginx
  command:
    cmd: /usr/sbin/pcs resource nginx restart
  become: true

- name: restart nginx
  command:
    cmd: /usr/sbin/pcs resource nginx restart
  become: true

- name: restart uwsgi
  command:
    cmd: /usr/sbin/pcs resource uwsgi restart
  become: true
