---
- name: Restart Fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Restart Coturn
  community.docker.docker_container:
    name: coturn
    state: started
    restart: true
    comparisons:
      '*': ignore
