---
# NGINX Ingress Controller: https://kubernetes.github.io/ingress-nginx/
#
# Sources: https://github.com/kubernetes/ingress-nginx
#
# Helm Chart:
# Releases: https://github.com/kubernetes/ingress-nginx/tags
# Sources: https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
# Helm Repo: https://kubernetes.github.io/ingress-nginx
# "helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
# Use: "helm show values ingress-nginx/ingress-nginx" to view configuration options.
#
# Installation:
# https://kubernetes.github.io/ingress-nginx/deploy/
# https://kubernetes.io/docs/concepts/services-networking/ingress/
- name: Add nginx-ingress-controller Helm repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  check_mode: false
  changed_when: false
- name: Install nginx-ingress-controller Helm chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: ingress-controller
    create_namespace: true
    values:
      "{{ ingress_chart_values }}"
