---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2004-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        swapfile_path: /swapfile
        swapfile_size_mb: 1024
        vm_swappiness: 50
        running_in_molecule: true
verifier:
  name: ansible
