- name: Install Proxy instances for bettermarks ({{ bettermarks_namespace }})
  vars:
    proxy_subdomain: "{{ bettermarks_proxy_subdomains[item] }}"
    bettermarks_subdomain: "{{ bettermarks_subdomains[item] }}"
    allow_cross_origin_credentials: "{{ item in bettermarks_credentials_allowed }}"
    instance_specific_chart_values:
      ingress:
        hostname: "{{ proxy_subdomain }}.{{ bettermarks_proxy_maindomain }}"
      serverBlock: "{{ lookup('template', 'nginx.conf.j2') }}"
  kubernetes.core.helm:
    name: "bettermarks-{{ item }}-proxy"
    chart_ref: bitnami/nginx
    update_repo_cache: true
    wait: true
    chart_version: "{{ bettermarks_proxy_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: "{{ bettermarks_namespace }}"
    values: "{{ instance_specific_chart_values | ansible.builtin.combine(bettermarks_proxy_chart_values, recursive=true) }}"
  loop: "{{ bettermarks_proxy_enabled_instances }}"
  tags: bettermarksproxy