---
- name: Create namespace for psql config
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    api_version: v1
    name: "{{ psql_namespace }}"
    kind: Namespace

- name: Create Secret for Postgres configuration
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    template: 'secret.yml.j2'
  register: postgres_secret

- name: Create configmap for config-script
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "psql-{{ psql_name }}-config-script"
        namespace: "{{ psql_namespace }}"
      data:
        config-script: "{{ lookup('template', 'config-script.sh.j2') }}"
  register: postgres_configscript

- name: Create Config Job
  kubernetes.core.k8s:
    state: "present"
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "psql-{{ psql_name }}-config-{{ 1000000 | random | hash('md5') }}"
        namespace: "{{ psql_namespace }}"
      spec:
        template:
          spec:
            volumes:
            - name: config-script
              configMap:
                name: "psql-{{ psql_name }}-config-script"
              # 711 in decimal is 457
                defaultMode: 457
            containers:
            - name:  psql-config
              image: schulcloud/infra-tools:{{ infratools_image_tag }}
              command:
                - /bin/bash
                - -c
              args:
                - /scripts/config-script
              resources:
                limits:
                  cpu: 1000m
                  memory: 2Gi
                requests:
                  cpu: 100m
                  memory: 1Gi
              volumeMounts:
              - name: config-script
                mountPath: /scripts/
              envFrom:
              - secretRef:
                  name: "psql-{{ psql_name }}-config"
            restartPolicy: Never
        backoffLimit: 4
  when: postgres_secret.changed or postgres_configscript.changed