---
# Install packages, define variables and groups, basic ufw configuration and run checks

- name: Install packages
  apt:
    name: 
      - pcs
      - pacemaker
      - python3-distutils
      - libxml2-utils
      - ufw
      - fail2ban
      - squid-openssl
      - golang
      - apparmor-utils

- name: Install passlib (required for htpasswd module)
  pip:
    name: passlib

- name: Set unique name of ha cluster (used for grouping)
  set_fact:
    unique_ha_group: "{{cluster_name }}_{{ project }}_{{ stage }}"

- name: Create ansible groups for the proxy clusters
  changed_when: false
  group_by:
    key: "{{ unique_ha_group }}"

- name: Determine if the host is a main node (first in group)
  set_fact:
    is_main_node: "{{ (groups[unique_ha_group] | sort | first) == inventory_hostname }}"

- name: Determine internal IP
  set_fact:
    internal_ip: "{{ ansible_all_ipv4_addresses | select('match', '10\\..*') | first }}"

# This requires that the domain of the nodes start with <name>-<index>. and the main domain with <name>.
# Alternative: Get IP from terraform output of a defined resource pool
- name: Determine main domain of the cluster
  set_fact:
    main_domain: "{{ inventory_hostname | regex_replace('^(?P<start>.+?)-\\d+\\.(?P<end>.+)$', '\\g<start>.\\g<end>') }}"

- name: Determine floating IP of the cluster via DNS
  set_fact:
    floating_ip: "{{ lookup('community.general.dig', main_domain )}}"
  when: is_main_node

- name: Check HA clusters are valid (There should be at least 2 nodes in a cluster)
  run_once: True
  debug:
    msg: "Cluster group: {{ item.key }}\nHosts: {{ item.value | sort }}"
  failed_when: item.value | length < 2
  loop: "{{ groups | dict2items | selectattr('key', 'match', cluster_name ~ '_.*')}}"

- name: Enable ufw (deny all)
  ufw:
    state: enabled
    policy: deny
  
- name: Allow SSH port
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Deactivate postfix (not necessary)
  service:
    name: postfix
    enabled: false
    state: stopped

# Automatic security updates are handled by unattended-upgrades. Sometimes a restart is necessary.
# In the night to Sunday for main node and night to Thursday for others
- name: Reboot weekly if necessary
  cron:
    name: "Weekly reboot for updates"
    weekday: "{{ 0 if is_main_node else 4 }}"
    hour: "0"
    minute: "21"
    job: "[ -f /var/run/reboot-required ] && /usr/sbin/reboot"