---
- name: Install packages
  apt:
    name: "{{ privacyidea_packages }}"
    state: present


- name: Create Python virtual environment
  python_virtualenv:
    path: "{{ privacyidea_dir }}/virtualenv"

- name: Activate virtual environment
  pip:
    virtualenv: "{{ privacyidea_dir }}/virtualenv"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"

- name: Install privacyidea dependencies
  pip:
    virtualenv: "{{ privacyidea_dir }}/virtualenv"
    requirements: "https://raw.githubusercontent.com/privacyidea/privacyidea/v{{ privacyidea_version }}/requirements.txt"


- name: Install privacyIDEA {{ privacyidea_version }}
  pip:
    virtualenv: "{{ privacyidea_dir }}/virtualenv"
    name: "privacyidea=={{ privacyidea_version }}"
