---
- name: Create user folder
  file:
    path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}"
    state: directory
    owner: "{{ tls_auth_file_permissions.owner | default(omit) }}"
    group: "{{ tls_auth_file_permissions.group | default(omit) }}"
    mode: "{{ tls_auth_file_permissions.mode | default(omit) }}"

- name: Get user private key from 1Password
  set_fact:
    user_key_content: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name=tls_auth_client_key_secret_name, vault=tls_auth_vault, session_shorthand=op_session_shorthand, credentials=op_credentials, ignore_not_found=true) }}"

- name: Create user private key file
  copy:
    content: "{{ user_key_content }}"
    dest: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_key_filename }}"
    owner: "{{ tls_auth_file_permissions.owner | default(omit) }}"
    group: "{{ tls_auth_file_permissions.group | default(omit) }}"
    mode: "{{ tls_auth_file_permissions.mode | default(omit) }}"
  when: user_key_content | length > 0

- name: Generate user private key
  community.crypto.openssl_privatekey:
    path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_key_filename }}"
    size: "{{ tls_auth_client_key_size }}"
    type: "{{ tls_auth_client_key_type }}"
  when: user_key_content | length == 0

- name: Upload user private key to 1Password
  dbildungscloud.onepwd.document:
    vault: "{{ tls_auth_vault }}"
    name: "{{ tls_auth_client_key_secret_name }}"
    path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_key_filename }}"
    session_shorthand: "{{ op_session_shorthand }}"
    credentials: "{{ op_credentials }}"
  when: user_key_content | length == 0

- name: Get user certificate from 1Password
  set_fact:
    user_cert_content: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name=tls_auth_client_cert_secret_name, vault=tls_auth_vault, session_shorthand=op_session_shorthand, credentials=op_credentials, ignore_not_found=true) }}"

- name: Create user certificate file
  copy:
    content: "{{ user_cert_content }}"
    dest: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_cert_filename }}"
    owner: "{{ tls_auth_file_permissions.owner | default(omit) }}"
    group: "{{ tls_auth_file_permissions.group | default(omit) }}"
    mode: "{{ tls_auth_file_permissions.mode | default(omit) }}"
  when: user_cert_content | length > 0

- name: Generate user certificate signing request
  community.crypto.openssl_csr:
    path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_csr_filename }}"
    common_name: "{{ tls_auth_client_cert_common_name }}"
    privatekey_path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_key_filename }}"
  when: user_cert_content | length == 0

- name: Generate user certificate
  community.crypto.x509_certificate:
    csr_path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_csr_filename }}"
    ownca_path: "{{ tls_auth_certs_dir }}/{{ tls_auth_ca_cert_filename }}"
    ownca_privatekey_path: "{{ tls_auth_certs_dir }}/{{ tls_auth_ca_key_filename }}"
    path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_cert_filename }}"
    provider: ownca
    ownca_not_after: "{{ tls_auth_client_cert_not_after }}"
  when: user_cert_content | length == 0

- name: Upload user certificate to 1Password
  dbildungscloud.onepwd.document:
    vault: "{{ tls_auth_vault }}"
    name: "{{ tls_auth_client_cert_secret_name }}"
    path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_cert_filename }}"
    session_shorthand: "{{ op_session_shorthand }}"
    credentials: "{{ op_credentials }}"
  when: user_cert_content | length == 0

- name: Create user pkcs12 file
  community.crypto.openssl_pkcs12:
    path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_p12_filename }}"
    privatekey_path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_key_filename }}"
    certificate_path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_cert_filename }}.crt"
    friendly_name: "{{ tls_auth_client_cert_common_name }}"
  when: user_cert_content | length == 0

- name: Upload user pkcs12 file to 1Password
  dbildungscloud.onepwd.document:
    vault: "{{ tls_auth_vault }}"
    name: "{{ tls_auth_client_pkcs12_secret_name }}"
    path: "{{ tls_auth_certs_dir }}/{{ tls_auth_client }}/{{ tls_auth_client_p12_filename }}"
    session_shorthand: "{{ op_session_shorthand }}"
    credentials: "{{ op_credentials }}"
  when: user_cert_content | length == 0
