---
- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ owasp_docker_compose_folder }}/docker-compose.yaml"
    owner: "{{ owasp_docker_compose_owner }}"
    group: "{{ owasp_docker_compose_group }}"
    mode: "0600"

- name: Copy .env
  template:
    src: env.j2
    dest: "{{ owasp_docker_compose_folder }}/.env"
    owner: "{{ owasp_docker_compose_owner }}"
    group: "{{ owasp_docker_compose_group }}"
    mode: "0600"

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ owasp_docker_compose_folder }}"
    remove_orphans: true
