---
- name: Install fail2ban
  apt:
    name: ['fail2ban']
    state: present

- name: Enable fail2ban
  service:
    name: fail2ban
    enabled: true
    state: started

- name: Create filter file for fail2ban general nginx errors
  copy:
    content: |
      [Definition]
      failregex = ^<HOST> - - \[.*\] ".*" (4\d\d|5\d\d) .+$
      ignoreregex =
    dest: /etc/fail2ban/filter.d/nginx-errors.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Fail2ban

- name: Create filter file for fail2ban, greenlight login errors
  copy:
    content: |
      [Definition]
      failregex = ^<HOST> - - \[.*\] ".*" (4\d\d|5\d\d) .*\/greenlight\/signin" ".*"$
      ignoreregex =
    dest: /etc/fail2ban/filter.d/greenlight-signin-errors.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Fail2ban

- name: Create jail file for fail2ban
  copy:
    content: |
      [nginx-http-auth]
      enabled = true
      port = {{ owasp_nginx_metrics_endpoints | map(attribute='public_port') | join(",") }}
      logpath = {{ owasp_nginx_logs_folder }}/*.log
      maxretry = 3
      bantime = 3600
      [nginx-errors]
      enabled    = true
      port       = http,https
      filter     = nginx-errors
      logpath    = {{ owasp_nginx_logs_folder }}/*.log
      maxretry   = 100
      bantime    = 3600
      findtime   = 600
      [greenlight-signin-errors]
      enabled    = true
      port       = http,https
      filter     = greenlight-signin-errors
      logpath    = {{ owasp_nginx_logs_folder }}/*.log
      maxretry   = 5
      bantime    = 3600
    dest: /etc/fail2ban/jail.d/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart Fail2ban
