---
- name: Check if certificates exists for "{{ server_name }}"
  stat:
    path: "/etc/letsencrypt/live/{{ server_name }}/privkey.pem"
  register: result

- name: Create Cert folder for "{{ server_name }}"
  file:
    state: directory
    path: "/etc/letsencrypt/live/{{ server_name }}"
    mode: "0750"
    owner: "{{ owasp_certificates_user }}"
    group: "{{ owasp_certificates_group }}"
  when: not result.stat.exists

- name: Create private key (RSA, 4096 bits) for "{{ server_name }}"
  community.crypto.openssl_privatekey:
    path: "/etc/letsencrypt/live/{{ server_name }}/privkey.pem"
    owner: "{{ owasp_certificates_user }}"
    group: "{{ owasp_certificates_group }}"
    mode: "0640"
  when: not result.stat.exists

- name: Create simple self-signed certificate for "{{ server_name }}"
  community.crypto.x509_certificate:
    path: "/etc/letsencrypt/live/{{ server_name }}/fullchain.pem"
    privatekey_path: "/etc/letsencrypt/live/{{ server_name }}/privkey.pem"
    provider: selfsigned
    owner: "{{ owasp_certificates_user }}"
    group: "{{ owasp_certificates_group }}"
  when: not result.stat.exists
