---
# Install Node Exporter
- name: Install and configure Node Exporter on Galera nodes
  include_role:
    name: prometheus.prometheus.node_exporter
  vars:
    node_exporter_version: "{{ node_exporter_version }}"
    node_exporter_web_listen_address: "{{ node_exporter_web_listen_address }}"

- name: Restart Node Exporter
  systemd:
    name: node_exporter
    enabled: true
    state: restarted