---
privacyidea_version: "3.8.1"
privacyidea_packages:
    - python3-venv
    - python3-pip
    - nginx
    - python3-mysqldb
    - uwsgi
    - uwsgi-plugin-python3
    - certbot
    - python3-certbot-nginx
    - mariadb-server
    - mariadb-client
privacyidea_dir: "/opt/privacyidea"
privacyidea_server_name: ""
privacyidea_mariadb_name: "privacyidea_mariadb"
# admin credentials
privacyidea_admin_password: ""
privacyidea_admin: "admin"
# nolden credentials
privacyidea_nolden_password: ""
privacyidea_nolden: "nolden"
# token-admin credentials
privacyidea_token_admin_password: ""
privacyidea_token_admin: "token-admin"
# fvm credentials
privacyidea_fvm_password: ""
privacyidea_fvm: "fvm"
# super credentials
privacyidea_super_password: ""
privacyidea_super: "super"
# seed-import credentials
privacyidea_seed_import_password: ""
privacyidea_seed_import: "seed-import"
# Mariadb user credentials:
privacyidea_db_user_password: ""
mariadb_user: "privacyidea_db"
# The default root user installed by mysql - almost always root
mysql_root_home: /root
privacyidea_mariadb_username: "root"
privacyidea_mariadb_password: ""

#The following values "user_realm", "sql_user_resolver", and "admin_realm" are taken from the admin2go dump file and are reflected in the policy table:
#- user_realm: "ucs_users"
#- sql_user_resolver: "ucs_users"
#- admin_realm: "super"

user_realm: "ucs_users"
sql_user_resolver: "ucs_users"
admin_realm: "super"
sql_admin_resolver: "superresolver"