---
privacyidea_mariadb_root_password: "" 
privacyidea_db_user_password: ""
privacyidea_mariadb_packages:
  - python3-mysqldb
  - mariadb-server
  - mariadb-client
privacyidea_version: "3.8.1"
privacyidea_admin_password: ""
privacyidea_enable_mariadb_setup: false
