---
- name: set motd
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0755'
  notify: Restart sshd

#Ensure pam_motd.so noupdate is present and uncommented in /etc/pam.d/sshd
- name: activate static motd
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^#?\s*session\s+optional\s+pam_motd\.so\s+noupdate'
    line: 'session    optional     pam_motd.so noupdate'
    state: present
    
#Ensure pam_motd.so motd=/run/motd.dynamic is commented out if present
- name: deactivate dynamic motd
  replace:
    path: /etc/pam.d/sshd
    regexp: '^(\s*)session\s+optional\s+pam_motd\.so\s+motd=/run/motd\.dynamic'
    replace: '#\1session    optional     pam_motd.so  motd=/run/motd.dynamic'
