---
  - name: Install fail2ban
    apt:
      name: ['fail2ban']
      state: latest
  
  # Following tasks(3) will throw errors when tested with molecule 
  # (service restart and handler cmd not compatible with container)
  # Used the molecule-notest tag to skip this in molecule
  - name: Enable fail2ban
    service:
      name: fail2ban
      enabled: true
      state: started
    tags: molecule-notest

  - name: Create default jail file for fail2ban
    copy:
      content: "{{ basic_fail2ban_jail_default }}"
      dest: "{{ basic_fail2ban_jail_default_path }}"
      owner: root
      group: root
      mode: 0644
    notify: Restart fail2ban
    tags: molecule-notest

  - name: Create sshd jail file for fail2ban
    copy:
      content: "{{ basic_fail2ban_jail_sshd }}"
      dest: "{{ basic_fail2ban_jail_sshd_path }}"
      owner: root
      group: root
      mode: 0644
    notify: Restart fail2ban
    tags: molecule-notest