---
  - name: Install fail2ban
    apt:
      name: ['fail2ban']
      state: latest
  
  # following tasks(3) will throw errors when tested with molecule (service restart and handler cmd not compatible with container)
  # used the molecule-notest tag to skip this in molecule
  - name: Enable fail2ban
    service:
      name: fail2ban
      enabled: true
      state: started
    tags: molecule-notest

  - name: Set ignoreip for fail2ban 
    lineinfile:
      path: /etc/fail2ban/jail.conf
      regexp: "^ignoreip"
      line: "ignoreip = {{ fail2ban_ignoreip }}"
    notify: Restart fail2ban
    tags: molecule-notest

  - name: Create jail file for fail2ban
    copy:
      content: "{{ fail2ban_jail_configuration }}"
      dest: "{{ fail2ban_jail_path }}"
      owner: root
      group: root
      mode: 0644
    notify: Restart fail2ban
    tags: molecule-notest