---
- name: restart nginx
  service: name=nginx state=restarted

- name: restart uWSGI
  systemd:
    name: uwsgi
    enabled: yes
    state: restarted
  become: true

- name: restart sshd
  service: name=sshd state=restarted
  
- name: restart fail2ban
  service: name=fail2ban state=restarted
