---
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: restart uwsgi
  systemd:
    name: uwsgi
    enabled: yes
    state: restarted
  become: true

- name: restart sshd
  service: name=sshd state=restarted
  
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  become: true