
---
- name: Copy privacyidea config file 'pi.cfg'
  template:
    src: pi.cfg.j2
    dest: /etc/privacyidea/pi.cfg
  notify: restart uwsgi

# Audit Keys (private.pem and public.pem) are used to sign and verify the audit logs, 
# ensuring that the audit log entries are tamper-proof and can be verified.
- name: Create public key file for subscription signature validation
  copy:
    dest: /etc/privacyidea/B1.pem
    content: "{{ subscription_auth_public_key }}"
    mode: '0644'

- name: Get Encfile from vault
  ansible.builtin.copy:
    content: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name='privacyidea', field='enckey', vault=vault, session_shorthand='ansible-run', credentials=op_credentials) | b64decode }}"
    dest: /etc/privacyidea/enckey
    mode: 0600
    group: www-data
    owner: www-data
        
- name: Get private audit key from vault
  ansible.builtin.copy:
    content: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name='privacyidea_audit', field='privatekey', vault=vault, session_shorthand='ansible-run', credentials=op_credentials)  }}"
    dest: /etc/privacyidea/private.pem
    mode: 0600
    group: www-data
    owner: www-data

- name: Get public audit key from vault
  ansible.builtin.copy:
    content: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name='privacyidea_audit', field='publickey', vault=vault, session_shorthand='ansible-run', credentials=op_credentials)  }}"
    dest: /etc/privacyidea/public.pem
    mode: 0600
    group: www-data
    owner: www-data
