
---
- name: Copy privacyidea config file 'pi.cfg'
  template:
    src: pi.cfg.j2
    dest: /etc/privacyidea/pi.cfg
  notify: restart uwsgi

# Audit Keys (private.pem and public.pem) are used to sign and verify the audit logs, 
# ensuring that the audit log entries are tamper-proof and can be verified.

- name: Get private audit key from vault
  ansible.builtin.copy:
    content: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name='privacyidea_audit_priv_key', field='private.pem', vault=vault, session_shorthand='ansible-run', credentials=op_credentials) | b64decode }}"
    dest: /etc/privacyidea/
    mode: 0600
    group: www-data
    owner: www-data

- name: Get public audit key from vault
  ansible.builtin.copy:
    content: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name='privacyidea_audit_public_key', field='public.pem', vault=vault, session_shorthand='ansible-run', credentials=op_credentials) | b64decode }}"
    dest: /etc/privacyidea/
    mode: 0600
    group: www-data
    owner: www-data

#old generate variant
# - name: Generate private key for PrivacyIDEA audit log
#   command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage create_audit_keys"
#   args:
#     chdir: "{{ privacyidea_dir }}"
#     creates: /etc/privacyidea/private.pem
#   become: true
#   when: is_main_node

# - name: Create public key file for subscription signature validation
#   copy:
#     dest: /etc/privacyidea/B1.pem
#     content: "{{ subscription_auth_public_key }}"
#     mode: '0644'
#     owner: www-data
#     group: www-data

# - name: Exchange AUDIT Keys
#   block:
#     - name: Get auth private key 
#       ansible.builtin.fetch:
#         src: "/etc/privacyidea/private.pem"
#         dest: "/tmp/certificate_sync_key_{{ unique_ha_group }}.auth.priv"
#         flat: true
#       when: is_main_node

#     - name: Get auth public key 
#       ansible.builtin.fetch:
#         src: "/etc/privacyidea/public.pem"
#         dest: "/tmp/certificate_sync_key_{{ unique_ha_group }}.auth.pub"
#         flat: true
#       when: is_main_node

#     - name: Set up auth private key
#       ansible.builtin.copy:
#         dest: "/etc/privacyidea/private.pem"
#         src: "/tmp/certificate_sync_key_{{ unique_ha_group }}.auth.priv"
#         group: www-data
#         owner: www-data
#         mode: '0600'
#       when: not is_main_node

#     - name: Set up auth public key
#       ansible.builtin.copy:
#         dest: "/etc/privacyidea/public.pem"
#         src: "/tmp/certificate_sync_key_{{ unique_ha_group }}.auth.pub"
#         group: www-data
#         owner: www-data
#         mode: '0644'
#       when: not is_main_node

#     - name: Delete local copies
#       file: 
#         path: "/tmp/certificate_sync_key_*" 
#         state: absent
#       delegate_to: localhost
#       ignore_errors: true
