---
- name: Setup Node_exporter in Galera nodes and privacyidea     
  vars:
    node_exporter_basic_auth_users:
        "exporter": "{{ privacyidea_galera_mysql_node_exporter }}"
  include_role:
    name:  prometheus.prometheus.node_exporter