bbb_prometheus_basic_auth_secret_mount_path: "/etc/bbb/{{ bbb_instance_name }}"
bbb_prometheus_basic_auth:
  username: ne_admin
  password_file: "{{ bbb_prometheus_basic_auth_secret_mount_path }}/password"

bbb_ionos_basic_auth_secret_mount_path: "/etc/bbb/{{ bbb_instance_name }}-ionos"
bbb_ionos_basic_auth:
  username: "{{ bbb_ionos_username }}"
  password_file: "{{ bbb_ionos_basic_auth_secret_mount_path }}/password"

bbb_prometheus_relabel_configs:
  # Rewrite hostname:port to hostname
  - source_labels: [__address__]
    target_label: instance
    regex: "([^:]+)(:[0-9]+)?"
    replacement: "${1}"

bbb_prometheus_labels:
  tenant: "{{ bbb_tenant }}"

bbb_servers_bbb_exporter_targets: "{{ bbb_servers if bbb_ebbba_exporters else bbb_servers | product([':9688']) | map('join', '') }}"
bbb_servers_node_exporter_targets: "{{ bbb_servers if bbb_ebbba_exporters else bbb_servers | product([':9100']) | map('join', '') }}"

bbb_turn_servers_coturn_exporter_targets: "{{ bbb_turn_servers | product([':9642']) | map('join', '') }}"
bbb_turn_servers_node_exporter_targets: "{{ bbb_turn_servers | product([':9100']) | map('join', '') }}"

bbb_prometheus_scalelite_job:
  job_name: "{{ bbb_instance_name }}-scalelite"
  scheme: https
  metrics_path: /metrics
  static_configs:
    - targets:
        - "{{ scalelite_host }}:9100"
      labels: "{{ bbb_prometheus_labels }}"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs: "{{ bbb_prometheus_relabel_configs }}"
bbb_prometheus_bbb_job:
  job_name: "{{ bbb_instance_name }}"
  scheme: https
  metrics_path: "{{ '/mon/bbb' if bbb_ebbba_exporters else '/metrics' }}"
  ionos_sd_config:
    datacenter_id: "{{ bbb_datacenter_id }}"
    basic_auth: "{{ bbb_ionos_basic_auth }}"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs:
    - source_labels: [__meta_ionos_server_name]
      regex: "bbb-.*"
      action: keep
bbb_prometheus_bbb_node_exporter_job:
  job_name: "{{ bbb_instance_name }}-node-exporter"
  scheme: https
  metrics_path: "{{ '/mon/node' if bbb_ebbba_exporters else '/metrics' }}"
  static_configs:
    - targets: "{{ bbb_servers_node_exporter_targets }}"
      labels: "{{ bbb_prometheus_labels }}"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs: "{{ bbb_prometheus_relabel_configs }}"
bbb_prometheus_turn_coturn_exporter_job:
  job_name: "{{ bbb_instance_name }}-turn-coturn-exporter"
  scheme: https
  metrics_path: /metrics
  static_configs:
    - targets: "{{ bbb_turn_servers_coturn_exporter_targets if bbb_turn_server_exporter_enabled else [] }}"
      labels: "{{ bbb_prometheus_labels }}"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs: "{{ bbb_prometheus_relabel_configs }}"
bbb_prometheus_turn_node_exporter_job:
  job_name: "{{ bbb_instance_name }}-turn-node-exporter"
  scheme: https
  metrics_path: /metrics
  static_configs:
    - targets: "{{ bbb_turn_servers_node_exporter_targets }}"
      labels: "{{ bbb_prometheus_labels }}"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs: "{{ bbb_prometheus_relabel_configs }}"


bbb_prometheus_scrape_config: "{{ bbb_prometheus_servers_only_scrape_config if bbb_servers_only else bbb_prometheus_full_scrape_config }}"

bbb_prometheus_full_scrape_config:
  - "{{ bbb_prometheus_scalelite_job }}"
  - "{{ bbb_prometheus_bbb_job }}"
  - "{{ bbb_prometheus_bbb_node_exporter_job }}"
  - "{{ bbb_prometheus_turn_coturn_exporter_job }}"
  - "{{ bbb_prometheus_turn_node_exporter_job }}"

bbb_prometheus_servers_only_scrape_config:
  - "{{ bbb_prometheus_bbb_job }}"
  - "{{ bbb_prometheus_bbb_node_exporter_job }}"

bbb_prometheus_volumes:
  - name: "{{ bbb_instance_name }}"
    secret:
      secretName: "{{ bbb_node_exporter_basic_auth_secret_name }}"
  - name: "{{ bbb_instance_name }}-ionos"
    secret:
      secretName: "{{ bbb_ionos_basic_auth_secret_name }}"

bbb_prometheus_volume_mounts:
  - name: "{{ bbb_instance_name }}"
    mountPath: "{{ bbb_prometheus_basic_auth_secret_mount_path }}"
    readOnly: true
  - name: "{{ bbb_instance_name }}-ionos"
    mountPath: "{{ bbb_ionos_basic_auth_secret_mount_path }}"
    readOnly: true
