---
bbb_prometheus_relabel_configs:
  # Drop not running servers
  - source_labels: [__meta_ionos_server_state]
    regex: "RUNNING"
    action: keep
  # Extract the port to a temporary label
  - source_labels: [__address__]
    target_label: __tmp_metrics_port
    regex: "([^:]+)(:[0-9]+)?"
    replacement: "${2}"
  # Use the IONOS server name as address to scrape
  - source_labels: [__meta_ionos_server_name, __tmp_metrics_port]
    target_label: __address__
    separator: ""
  # Removes the port from the hostname
  - source_labels: [__address__]
    target_label: instance
    regex: "([^:]+)(:[0-9]+)?"
    replacement: "${1}"
  # Add the tenant label
  - target_label: tenant
    replacement: "{{ tenant }}"

bbb_prometheus_scalelite_relabel_configs:
  # Rewrite hostname:port to hostname
  - source_labels: [__address__]
    target_label: instance
    regex: "([^:]+)(:[0-9]+)?"
    replacement: "${1}"
  # Add the tenant label
  - target_label: tenant
    replacement: "{{ tenant }}"

bbb_datacenter_ionos_sd_configs: |
  {% for id in bbb_datacenter_ids %}
  - datacenter_id: "{{ id }}"
    basic_auth:
      {{ bbb_ionos_basic_auth | to_nice_yaml | indent(4) }}
    port: {{ 443 if bbb_ebbba_exporters else 9688 }}
    refresh_interval: 15s
  {% endfor %}
bbb_turn_coturn_datacenter_ionos_sd_configs: |
  {% for id in bbb_datacenter_ids %}
  - datacenter_id: "{{ id }}"
    basic_auth:
      {{ bbb_ionos_basic_auth | to_nice_yaml | indent(4) }}
    port: 9642
    refresh_interval: 15s
  {% endfor %}
bbb_turn_node_datacenter_ionos_sd_configs: |
  {% for id in bbb_datacenter_ids %}
  - datacenter_id: "{{ id }}"
    basic_auth:
      {{ bbb_ionos_basic_auth | to_nice_yaml | indent(4) }}
    port: 9100
    refresh_interval: 15s
  {% endfor %}

bbb_prometheus_scalelite_node_exporter_job:
  job_name: "{{ bbb_instance_name }}-scalelite"
  scheme: https
  metrics_path: /metrics
  static_configs:
    - targets:
        - "{{ scalelite_host }}:9100"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs: "{{ bbb_prometheus_scalelite_relabel_configs }}"
  scrape_interval: "{{ bbb_monitoring_scrape_interval }}"
  scrape_timeout: "{{ bbb_monitoring_scrape_timeout }}"

bbb_prometheus_scalelite_autoscaler_job:
  job_name: "{{ bbb_instance_name }}-scalelite-autoscaler"
  scheme: https
  metrics_path: /metrics
  static_configs:
    - targets:
        - "{{ scalelite_host }}:9200"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs: "{{ bbb_prometheus_scalelite_relabel_configs }}"
  scrape_interval: "{{ bbb_monitoring_scrape_interval }}"
  scrape_timeout: "{{ bbb_monitoring_scrape_timeout }}"

bbb_prometheus_bbb_job:
  job_name: "{{ bbb_instance_name }}"
  scheme: https
  metrics_path: "{{ '/mon/bbb' if bbb_ebbba_exporters else '/metrics' }}"
  ionos_sd_configs: "{{ bbb_datacenter_ionos_sd_configs | from_yaml }}"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs: "{{ [{'source_labels': ['__meta_ionos_server_name'], 'regex': 'bbb-.*', 'action': 'keep'}] + bbb_prometheus_relabel_configs }}"
  scrape_interval: "{{ bbb_monitoring_scrape_interval }}"
  scrape_timeout: "{{ bbb_monitoring_scrape_timeout }}"

bbb_prometheus_bbb_node_exporter_job:
  job_name: "{{ bbb_instance_name }}-node-exporter"
  scheme: https
  metrics_path: "{{ '/mon/node' if bbb_ebbba_exporters else '/metrics' }}"
  ionos_sd_configs: "{{ bbb_datacenter_ionos_sd_configs | from_yaml }}"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs: "{{ [{'source_labels': ['__meta_ionos_server_name'], 'regex': 'bbb-.*', 'action': 'keep'}] + bbb_prometheus_relabel_configs }}"
  scrape_interval: "{{ bbb_monitoring_scrape_interval }}"
  scrape_timeout: "{{ bbb_monitoring_scrape_timeout }}"

bbb_prometheus_bbb_blackbox_exporter_job:
  job_name: "{{ bbb_instance_name }}-blackbox-exporter"
  # scheme: http
  metrics_path: /probe
  params:
    module: ["http_2xx"]
  ionos_sd_configs: "{{ bbb_datacenter_ionos_sd_configs | from_yaml }}"
  relabel_configs:
    - source_labels: [__meta_ionos_server_name]
      regex: "bbb-.*"
      action: keep
    # Drop not running servers
    - source_labels: [__meta_ionos_server_state]
      regex: "RUNNING"
      action: keep
    # Prefix https:// and append /bigbluebutton to the hostname
    - source_labels: [__meta_ionos_server_name]
      target_label: __param_target
      regex: "(.*)"
      replacement: "https://${1}/bigbluebutton"
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: "{{ bbb_blackbox_exporter_url | default('prometheus-blackbox-exporter:9115') }}"
    - target_label: tenant
      replacement: "{{ tenant }}"
  scrape_interval: "{{ bbb_monitoring_scrape_interval }}"
  scrape_timeout: "{{ bbb_monitoring_scrape_timeout }}"

bbb_prometheus_turn_coturn_exporter_job:
  job_name: "{{ bbb_instance_name }}-turn-coturn-exporter"
  scheme: https
  metrics_path: /metrics
  ionos_sd_configs: "{{ bbb_turn_coturn_datacenter_ionos_sd_configs | from_yaml }}"
  relabel_configs: "{{ [{'source_labels': ['__meta_ionos_server_name'], 'regex': 'turn-.*', 'action': 'keep'}] + bbb_prometheus_relabel_configs }}"
  scrape_interval: "{{ bbb_monitoring_scrape_interval }}"
  scrape_timeout: "{{ bbb_monitoring_scrape_timeout }}"

bbb_prometheus_turn_node_exporter_job:
  job_name: "{{ bbb_instance_name }}-turn-node-exporter"
  scheme: https
  metrics_path: /metrics
  ionos_sd_configs: "{{ bbb_turn_node_datacenter_ionos_sd_configs }}"
  basic_auth: "{{ bbb_prometheus_basic_auth }}"
  relabel_configs: "{{ [{'source_labels': ['__meta_ionos_server_name'], 'regex': 'turn-.*', 'action': 'keep'}] + bbb_prometheus_relabel_configs }}"
  scrape_interval: "{{ bbb_monitoring_scrape_interval }}"
  scrape_timeout: "{{ bbb_monitoring_scrape_timeout }}"


bbb_prometheus_scrape_config: "{{ bbb_prometheus_servers_only_scrape_config + (bbb_prometheus_scalelite_scrape_config if not bbb_servers_only else []) + ([bbb_prometheus_turn_coturn_exporter_job] if bbb_turn_server_exporter_enabled else []) }}"

bbb_prometheus_servers_only_scrape_config:
  - "{{ bbb_prometheus_bbb_job }}"
  - "{{ bbb_prometheus_bbb_node_exporter_job }}"
  - "{{ bbb_prometheus_bbb_blackbox_exporter_job }}"

bbb_prometheus_scalelite_scrape_config:
  - "{{ bbb_prometheus_scalelite_node_exporter_job }}"
  - "{{ bbb_prometheus_scalelite_autoscaler_job }}"
  - "{{ bbb_prometheus_turn_node_exporter_job }}"

bbb_prometheus_basic_auth_secret_mount_path: "/etc/bbb/{{ bbb_instance_name }}"
bbb_prometheus_basic_auth:
  username: ne_admin
  password_file: "{{ bbb_prometheus_basic_auth_secret_mount_path }}/password"

bbb_prometheus_volumes:
  - name: "{{ bbb_instance_name }}"
    secret:
      secretName: "{{ bbb_node_exporter_basic_auth_secret_name }}"
  - name: "{{ bbb_instance_name }}-ionos"
    secret:
      secretName: "{{ bbb_ionos_basic_auth_secret_name }}"

bbb_ionos_basic_auth_secret_mount_path: "/etc/bbb/{{ bbb_instance_name }}-ionos"
bbb_ionos_basic_auth:
  username: "{{ bbb_prometheus_ionos_username }}"
  password_file: "{{ bbb_ionos_basic_auth_secret_mount_path }}/{{ bbb_ionos_basic_auth_secret_key }}"

bbb_prometheus_volume_mounts:
  - name: "{{ bbb_instance_name }}"
    mountPath: "{{ bbb_prometheus_basic_auth_secret_mount_path }}"
    readOnly: true
  - name: "{{ bbb_instance_name }}-ionos"
    mountPath: "{{ bbb_ionos_basic_auth_secret_mount_path }}"
    readOnly: true
