---

  - name: create groups
    group:
      name: "{{ item.name }}"
      gid: "{{ item.gid }}"
      state: present
    when: item.name is defined and ((item.allhosts is defined and item.allhosts == True) or (item.hosts is defined and inventory_hostname in item.hosts))
    with_items:
      - "{{ present_groups }}"

  - getent:
      database: group
      split: ':'

  - name: clean up root authorized_keys
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', 'sshkeys/technicaluser.pub') }}"
      exclusive: True

  - name: create users
    user:
      name: "{{ item.name }}"
      uid: "{{ item.uid }}"
      shell: /bin/bash
      state: present
    vars:
      vm_permissions: "{{ item.permissions.vms | default({}) }}"
      allowed: "{{ (vm_permissions.allhosts | default(false)) or (inventory_hostname in (vm_permissions.hosts | default([]))) }}"
    when: item.name is defined and allowed
    with_items:
      - "{{ present_users }}"

  - getent:
      database: group
      split: ':'

  - name: add users to groups
    user:
      name: "{{ item.0.name }}"
      groups: "{{ item.1 }}"
      append: yes
      state: present
    vars:
      vm_permissions: "{{ item.0.permissions.vms | default({}) }}"
      allowed: "{{ (vm_permissions.allhosts | default(false)) or (inventory_hostname in (vm_permissions.hosts | default([]))) }}"
    when: item.0.name is defined and allowed and item.1 in ansible_facts.getent_group
    with_subelements:
      - "{{ present_users }}"
      - permissions.vms.groups

  - name: Set up authorized keys for users
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ lookup('file', 'sshkeys/{{ item.name }}.pub') }}"
      exclusive: False
    vars:
      vm_permissions: "{{ item.permissions.vms | default({}) }}"
      allowed: "{{ (vm_permissions.allhosts | default(false)) or (inventory_hostname in (vm_permissions.hosts | default([]))) }}"
    when: item.name is defined and allowed
    with_items:
      - "{{ present_users }}"

  - name: set password for technicaluser 
    user: 
      name: technicaluser
      update_password: always
      password: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name='technicaluser', vault='Infrastructure', session_shorthand='ansible-run', field='password')| string | password_hash('sha512')}}"

  - name: remove users ( absent general )
    user:
      name: "{{ item.name }}"
      shell: /bin/false
      state: absent
      remove: yes
    with_items:
      - "{{ absent_users }}"

  - name: remove users ( absent host )
    user:
      name: "{{ item.name }}"
      shell: /bin/false
      state: absent
      remove: yes
    vars:
      vm_permissions: "{{ item.permissions.vms | default({}) }}"
      allowed: "{{ (vm_permissions.allhosts | default(false)) or (inventory_hostname in (vm_permissions.hosts | default([]))) }}"
    when: item.name is defined and not allowed
    with_items:
      - "{{ present_users }}"

  - name: Remove orphaned home directories
    #  This task asumes that the home directory of an already deleted user is stored with the name of the user below /home
    #  and will use absent_users as base for the operation
    ansible.builtin.file:
        path: /home/{{ item.name }}
        state: absent
    with_items:
      - "{{ absent_users }}" 

  # make it possible for devops group to sudo 
  - name: Make sudo without password for devops group possible
    copy:
      src: devops_nopasswd
      dest: /etc/sudoers.d/devops_nopasswd
      mode: 0440

  - name: set sshd_config 
    ansible.builtin.copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0644
    notify: restart sshd