---
#- name: Copy Nginx configuration
#  template:
#    src: nginx_privacyidea.conf.j2
#    dest: /etc/nginx/conf.d/privacyidea.conf
#  notify: restart nginx

# Increasing the hash table size to 128, to provid more buckets for Nginx to store and look up the server name
- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify:
    - restart nginx

- name: create SSL directory 
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'
  become: true


- name: Generate SSL certificate and key
  command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/privacyidea.key -out /etc/nginx/ssl/privacyidea.crt -subj "/CN={{ server_name }}"
  #shell: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/privacyidea.key -out /etc/nginx/ssl/privacyidea.crt -subj "/CN={{ server_name}}"
  become: true

- name: Update Nginx configuration for SSL
  template:
    src:  nginx_privacyidea.conf.j2
    dest: /etc/nginx/conf.d/privacyidea.conf
    mode: '0644'
  notify:
    - Restart Nginx
  become: true
