---
- name: Configure database connection
  template:
    src: pi.cfg.j2
    dest: /etc/privacyidea/pi.cfg

- name: Copy PrivacyIDEA WSGI script
  template:
    src: privacyideaapp.py.j2
    dest: /etc/privacyidea/privacyideaapp.py

- name: Create database tables
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage create_tables"

- name: Stamp the database schema
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage db stamp head -d {{ privacyidea_dir }}/virtualenv/lib/privacyidea/migrations/"

- name: Create SQL resolver configuration file
  template:
    src: user_sql_resolver_config.ini.j2
    dest: /etc/privacyidea/user_sql_resolver_config.ini
    owner: www-data
    group: www-data
    mode: '0600'

- name: Create SQL admin resolver
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage resolver create {{ sql_admin_resolver }} sqlresolver /etc/privacyidea/user_sql_resolver_config.ini"
  become: true
  become_user: www-data

- name: Create admin realm
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage realm create {{ admin_realm }} {{ sql_admin_resolver }}"
  become: true
  become_user: www-data
