---
# The following admin users are defined in policies from dump file:
# - admin : defined in superuser_internal policy
# - token-admin : defined in token-admin policy
# - seed-import
# To ensure data integrity with the dump file, we will create them in PrivacyIDEA.
# The existing admin users will be removed because they are imported from a dump file and will be overwritten. 
# We will delete the current admin users from the database and manually recreate them afterward.

- name: "Create PrivacyIDEA admin users"
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage admin add {{ item }} --password {{ 'vars[' + item + '_password]' }}"
  become: true
  become_user: www-data
  loop: "{{ privacyidea_admin_users }}"

