---
- name: Generate encryption key
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage create_enckey"
  args:
    creates: /etc/privacyidea/enckey

- name: Generate PI_PEPPER
  ansible.builtin.shell: |
    PI_PEPPER=$(tr -dc A-Za-z0-9_ < /dev/urandom | head -c24)
    sed -i "/^PI_PEPPER/c\PI_PEPPER = '$PI_PEPPER'" /etc/privacyidea/pi.cfg

- name: Generate SECRET_KEY
  ansible.builtin.shell: |
    SECRET_KEY=$(tr -dc A-Za-z0-9_ < /dev/urandom | head -c24)
    sed -i "/^SECRET_KEY/c\SECRET_KEY = '$SECRET_KEY'" /etc/privacyidea/pi.cfg

- name: Generate private key for audit log
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage create_audit_keys"
  args:
    chdir: "{{ privacyidea_dir }}"
    creates: /etc/privacyidea/private.pem

- name: Set PrivacyIDEA file permissions
  file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: "{{ item.mode }}"
  loop:
    - { path: '/etc/privacyidea/enckey', mode: '0600' }
    - { path: '/etc/privacyidea/pi.cfg', mode: '0644' }
    - { path: '/etc/privacyidea/privacyideaapp.py', mode: '0755' }
    - { path: '/etc/privacyidea/private.pem', mode: '0600' }
    - { path: '/etc/privacyidea/public.pem', mode: '0644' }
