
---
- name: Copy privacyidea config file 'pi.cfg'
  template:
    src: pi.cfg.j2
    dest: /etc/privacyidea/pi.cfg
  notify: restart uWSGI

#Audit Keys (private.pem and public.pem) are used to sign and verify the audit logs, 
#ensuring that the audit log entries are tamper-proof and can be verified.
- name: Generate private key for PrivacyIDEA audit log
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage create_audit_keys"
  args:
    chdir: "{{ privacyidea_dir }}"
    creates: /etc/privacyidea/private.pem
  become: true
