---
- name: Copy the privacyideadata_import_and_cleanup script to /etc/privacyidea
  copy:
    src: privacyide_adata_import_and_cleanup.sh
    dest: /etc/privacyidea/privacyidea_data_import_and_cleanup.sh
    owner: www-data
    group: www-data
    mode: '0755'

- name: Execute the privacyidea_data_import_and_cleanup.sh script
  shell: /etc/privacyidea/privacyidea_data_import_and_cleanup.sh
  args:
    executable: /bin/bash
