---
- name: Install packages
  apt:
    name: "{{ privacyidea_packages }}"
    state: present

- name: Install packages
  apt:
    name: "{{ privacyidea_packages }}"
    state: present
    update_cache: yes 
