---
- name: Install packages
  apt:
    name: "{{ privacyidea_packages }}"
    state: present

- name: Create {{ privacyidea_dir }} directory for virtual environment
  file:
    path: "{{ privacyidea_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Install virtualenv
  pip:
    name: virtualenv
  become: true

- name: Create Python virtual environment
  command: python3 -m venv "{{ privacyidea_dir }}/virtualenv"
  args:
    creates: "{{ privacyidea_dir }}/virtualenv"
  become: true

- name: Install privacyidea dependencies
  pip:
    virtualenv: "{{ privacyidea_dir }}/virtualenv"
    requirements: "https://raw.githubusercontent.com/privacyidea/privacyidea/v{{ privacyidea_version }}/requirements.txt"

- name: Install privacyIDEA {{ privacyidea_version }}
  pip:
    virtualenv: "{{ privacyidea_dir }}/virtualenv"
    name: "privacyIDEA=={{ privacyidea_version }}"

- name: Create log directory for PrivacyIDEA
  file:
    path: /var/log/privacyidea
    state: directory
    recurse: yes
    mode: '0755'
  become: true

- name: Create log file for PrivacyIDEA
  file:
    path: /var/log/privacyidea/privacyidea.log
    state: touch
    mode: '0644'
  become: true

- name: Ensure privacyidea directory to store 'pi.cfg' file
  file:
    path: /etc/privacyidea
    state: directory
    mode: '0755'
  become: true

- name: Configure PrivacyIDEA
  template:
    src: pi.cfg.j2
    dest: /etc/privacyidea/pi.cfg
    mode: '0644'
  become: true
#this step is added cause :PermissionError: [Errno 13] Permission denied: '/var/log/privacyidea/privacyidea.log' when i run pi-manage createdb 
#to test SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://{{ privacyidea_mariadb_username }}:{{ privacyidea_mariadb_password }}@10.7.240.1/spshinfra-dev-schulportal-01'

- name: Set permissions for PrivacyIDEA log file
  file:
    path: /var/log/privacyidea/privacyidea.log
    owner: www-data
    group: www-data
    mode: 0644
  become: true

- name: Create mariadb database
  mysql_db:
    name: "{{ privacyidea_mariadb_name }}"
    state: present
    login_user: "{{ privacyidea_mariadb_username }}"
    login_password: "{{ privacyidea_mariadb_password }}"
    login_host: "{{ privacyidea_mariadb_private_ip }}"
  become: true
