---
- name: Install MariaDB for PrivacyIDEA
  apt:
    name: "{{ mariadb_packages }}"
    state: present

- name: Configure MariaDB for PrivacyIDEA
  mysql_db:
    name: privacyidea_db
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present

- name: Create PrivacyIDEA User in MariaDB
  mysql_user:
    name: privacyidea_user
    password: "{{ db_user_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    priv: 'privacyidea_db.*:ALL'
    state: present

#https://privacyidea.readthedocs.io/en/latest/installation/ubuntu.html

- name: Add PrivacyIDEA Repository
  become: true
  block:
    - name: Download the signing key
      apt_key:
        url: https://lancelot.netknights.it/NetKnights-Release.asc
        state: present

    - name: Add repository
      apt_repository:
        repo: 'deb http://lancelot.netknights.it/community/jammy/stable jammy main' #For Ubuntu 22.04 LTS, use jammy.
        state: present

- name: Update APT package
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install PrivacyIDEA with Nginx
  apt:
    name: privacyidea-nginx=3.9.2-1jammy # This command will install PrivacyIDEA and Nginx, along with any necessary dependencies.
    state: present
