---
- name: Install required system packages
  apt:
    name: "{{ privacyidea_packages }}"
    state: present

- name: Install pip and virtualenv
  pip:
    name:
      - pip
      - virtualenv
    state: latest