---
- name: Install packages
  apt:
    name: "{{ privacyidea_packages }}"
    state: present

- name: Create Python virtual environment
  command:
    cmd: python3 -m venv "{{ privacyidea_dir }}/virtualenv"
  args:
    creates: "{{ privacyidea_dir }}/virtualenv"

#- name: Activate virtual environment
#  shell: "source {{ privacyidea_dir }}/virtualenv/bin/activate"

- name: Activate virtual environment
  command: "{{ privacyidea_dir }}/virtualenv/bin/activate"



- name: Install privacyidea dependencies
  pip:
    virtualenv: "{{ privacyidea_dir }}/virtualenv"
    requirements: "https://raw.githubusercontent.com/privacyidea/privacyidea/v{{ privacyidea_version }}/requirements.txt"

- name: Install privacyIDEA {{ privacyidea_version }}
  pip:
    virtualenv: "{{ privacyidea_dir }}/virtualenv"
    name: "privacyidea=={{ privacyidea_version }}"