#Encryption Key is used to encrypt sensitive data within PrivacyIDEA, such as tokens and passwords
#https://privacyidea.readthedocs.io/en/latest/installation/system/pi-manage.html#pimanage

- name: Generate encryption key for PrivacyIDEA
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage create_enckey"
  args:
    creates: /etc/privacyidea/enckey
  become: true

# This is used to encrypt the admin passwords
- name: Generate PI_PEPPER for PrivacyIDEA
  shell: |
    PI_PEPPER=$(tr -dc A-Za-z0-9_ < /dev/urandom | head -c24)
    echo "PI_PEPPER = '$PI_PEPPER'" >> /etc/privacyidea/pi.cfg
  become: true

# This is used to encrypt the auth_token
- name: Generate SECRET_KEY for PrivacyIDEA
  shell: |
    SECRET_KEY=$(tr -dc A-Za-z0-9_ < /dev/urandom | head -c24)
    echo "SECRET_KEY = '$SECRET_KEY'" >> /etc/privacyidea/pi.cfg
  become: true


#Audit Keys (private.pem and public.pem) are used to sign and verify the audit logs, 
#ensuring that the audit log entries are tamper-proof and can be verified.
#https://privacyidea.readthedocs.io/en/latest/installation/system/pi-manage.html#pimanage
- name: Generate private key for PrivacyIDEA audit log
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage create_audit_keys"
  args:
    chdir: "{{ privacyidea_dir }}"
    creates: /etc/privacyidea/private.pem
  become: true

- name: Set PrivacyIDEA file permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: "{{ item.mode }}"
  loop:
    - { path: '/etc/privacyidea/enckey', mode: '0600' }
    - { path: '/etc/privacyidea/pi.cfg', mode: '0644' }
    - { path: '/etc/privacyidea/privacyideaapp.py', mode: '0755' }
    - { path: '/etc/privacyidea/private.pem', mode: '0600' }
    - { path: '/etc/privacyidea/public.pem', mode: '0644' }
  become: true
  notify: restart uWSGI