#Encryption Key is used to encrypt sensitive data within PrivacyIDEA, such as tokens and passwords
- name: Generate encryption key for PrivacyIDEA
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage create_enckey"
  args:
    creates: /etc/privacyidea/enckey
  become: true

- name: Set permissions for encryption key
  file:
    path: /etc/privacyidea/enckey
    owner: www-data
    group: www-data
    mode: '0600'
  become: true

#Audit Keys (private.pem and public.pem) are used to sign and verify the audit logs, ensuring that the audit log entries are tamper-proof and can be verified.
- name: Generate private key for PrivacyIDEA audit log
  command: "{{ privacyidea_dir }}/virtualenv/bin/pi-manage create_audit_keys"
  args:
    creates: /etc/privacyidea
  become: true