---
# Remove default Nginx configuration to avoid conflict
#Erreur from AWX:Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code
- name: Remove default and PrivacyIDEA Nginx site configurations
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-available/privacyidea
  become: true
  notify:
    - restart nginx

# Increasing the hash table size to 128, to provid more buckets for Nginx to store and look up the server name
- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify:
    - restart nginx

# remeber that you should create ssl cert manually
# sudo certbot certonly --nginx -d privacyidea.staging.spsh.dbildungsplattform.de -m devops@dbildunsplattform.de --pre-hook "ufw allow IN 80/tcp" --post-hook "ufw delete allow IN 80/tcp"
# Configures Nginx to serve privacyIDEA
- name: Copy Nginx configuration
  template:
    src: nginx_privacyidea.conf.j2
    dest: /etc/nginx/sites-available/privacyidea.conf
  notify: restart nginx

- name: Create symbolic link to enable PrivacyIDEA site
  file:
    src: /etc/nginx/sites-available/privacyidea.conf
    dest: /etc/nginx/sites-enabled/privacyidea.conf
    state: link
  notify:
    - restart nginx
  become: true

- name: Allow HTTPS traffic through firewall
  ufw:
    rule: allow
    port: '443'
    proto: tcp
  become: true

- name: Reload firewall rules
  command: ufw reload
  become: true