---

- name: Install packages
  apt:
    name: 
      - ufw
      - fail2ban

- name: Enable ufw (deny all)
  ufw:
    state: enabled
    policy: deny
  
- name: Allow SSH port
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTPS through the firewall
  ufw:
    rule: allow
    port: "443"
    proto: tcp

# Automatic security updates are handled by unattended-upgrades. Sometimes a restart is necessary.
# In the night to Sunday
- name: Reboot weekly if necessary
  cron:
    name: "Weekly reboot for updates"
    weekday: "0"
    hour: "0"
    minute: "21"
    job: "[ -f /var/run/reboot-required ] && /usr/sbin/reboot"

- name: Copy PrivacyIDEA Fail2Ban filter
  template:
    src: privacyidea.conf.j2
    dest: /etc/fail2ban/filter.d/privacyidea.conf
  notify: restart fail2ban

- name: Copy PrivacyIDEA Fail2Ban jail configuration
  template:
    src: privacyidea-jail.conf.j2
    dest: /etc/fail2ban/jail.d/privacyidea.conf
  notify: restart fail2ban

- name: copy ssh-jail for fail2ban
  copy:
    src: sshd.local
    dest: /etc/fail2ban/jail.d/sshd.local
    owner: root
    group: root
    mode: 0744
  notify: restart fail2ban
