---
- name: Enable ufw (deny all)
  ufw:
    state: enabled
    policy: deny

- name: Allow SSH port
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTPS through the firewall
  ufw:
    rule: allow
    port: "443"
    proto: tcp

# Automatic security updates are handled by unattended-upgrades. Sometimes a restart is necessary.
# In the night to Sunday
- name: Reboot weekly if necessary
  cron:
    name: "Weekly reboot for updates"
    weekday: "0"
    hour: "0"
    minute: "21"
    job: "[ -f /var/run/reboot-required ] && /usr/sbin/reboot"

- name: Copy PrivacyIDEA Fail2Ban filter
  template:
    src: auth-fail2ban.conf.j2
    dest: /etc/fail2ban/filter.d/auth-fail2ban.conf
  notify: restart fail2ban

- name: Copy PrivacyIDEA Fail2Ban jail configuration
  template:
    src: privacyidea-jail.conf.j2
    dest: /etc/fail2ban/jail.d/privacyidea-jail.conf
  notify: restart fail2ban

- name: copy ssh-jail for fail2ban
  template:
    src: sshd.local.j2
    dest: /etc/fail2ban/jail.d/sshd.local
    owner: www-data
    group: www-data
    mode: 0744
  notify: restart fail2ban
