---
## sshd pulls its image from dockerhub, to prevent the pull limit we use a docker pull secret token
image_pull_token_enabled: true
## image_pull_token_secret secret value is handed over by playbook on deployment
# image_pull_token_secret: []
