---
owasp_docker_volumes_folder: /var/docker_volumes
owasp_docker_compose_folder: /etc/owasp
owasp_docker_compose_owner: root
owasp_docker_compose_group: root

owasp_certbot_installed: false
owasp_certbot_image_repository: certbot/certbot
# v2.11.0
owasp_certbot_image_digest: sha256:ddf9e5d226a56e886986838fa0ebedc0237511c78664352e8d0f4346ee022cd8
# Custom UID to run certbot as
owasp_certbot_user_id: 9999
owasp_certbot_group_id: 9999
# owasp_certbot_terraform_telekom_os_access_key:
# owasp_certbot_terraform_telekom_os_secret_key:
# owasp_certbot_terraform_telekom_domain:
# owasp_certbot_terraform_telekom_tenant:
# owasp_certbot_terraform_telekom_dns_zone_id:
# owasp_certbot_terraform_state_bucket:
# owasp_certbot_terraform_state_key:
# owasp_certbot_terraform_state_region:
# owasp_certbot_terraform_state_endpoint:
owasp_certbot_terraform_version: 1.5.4
owasp_certbot_resources:
  reservations:
    cpus: '0.1'
    memory: 10M
  limits:
    cpus: '0.3'
    memory: 70M
# owasp_letsencrypt_email:

owasp_nginx_image: owasp/modsecurity-crs:4.12.0-nginx-alpine-202503230103
owasp_nginx_user_id: 101
owasp_nginx_group_id: "{{ owasp_certbot_group_id }}"
owasp_nginx_logs_folder: /var/log/nginx
owasp_nginx_dhparam_size: 4096
owasp_nginx_worker_processes: auto
owasp_nginx_ssl: true
owasp_nginx_resources:
  reservations:
    cpus: '0.1'
    memory: 15M
  limits:
    cpus: "{{ ansible_facts['processor_vcpus'] / 2 }}"
    memory: "{{ ansible_facts['memory_mb']['real']['total'] / 2 }}M"
owasp_nginx_metrics_endpoints:
  - name: node-exporter
    public_port: 9100
    private_port: 9099
  - name: cadvisor
    public_port: 9300
    private_port: 9299
  - name: postgres-exporter
    public_port: 9188
    private_port: 9187

owasp_docker_net: "192.168.64.0/24"
owasp_modsec_mode: DetectionOnly  # Either DetectionOnly or '"ON"'
# Paranoia level for ModSecurity 
owasp_modsec_level: 1
# Debug Level for logging
owasp_modsec_debuglevel: 1 
owasp_modsec_reportlevel: 1
owasp_modsec_logs_folder: /var/log/modsec
owasp_modsec_outbound_anomaly: 4
owasp_modsec_inbound_anomaly: 5
owasp_modsec_before: |
  # Dummy comment

owasp_modsec_after: |
  SecRule REMOTE_ADDR "@ipMatch {{ owasp_docker_net }}"                     "id:1001, phase:1, pass, nolog,   allow"    
  SecRule REQUEST_URI "@beginsWith /fsapi"                                      "id:1002, phase:1, pass, nolog,   ctl:ruleRemoveById=932230"  
  SecRule REQUEST_URI "@beginsWith /fsapi"                                      "id:1003, phase:1, pass, nolog,   ctl:ruleRemoveById=932250"
  SecRule REQUEST_URI "@beginsWith /fsapi"                                      "id:1004, phase:1, pass, nolog,   ctl:ruleRemoveById=949110"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/rooms"                      "id:1005, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/room_settings"              "id:1006, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/sessions/signout.json"      "id:1007, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/users"                      "id:1008, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/admin/site_settings"        "id:1009, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/admin/rooms_configurations" "id:1010, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/admin/users"                "id:1011, phase:1, pass, nolog,   allow"
  SecAction "id:980145,phase:5,pass,t:none,log,noauditlog, msg:'Incoming and Outgoing Score: %{TX.ANOMALY_SCORE} %{TX.OUTBOUND_ANOMALY_SCORE}'"
  SecRuleRemoveById 980130

owasp_hostname: "{{ inventory_hostname }}"
owasp_letsencrypt_folder: /etc/letsencrypt
owasp_metrics_basic_auth_username: metrics-user
# owasp_metrics_basic_auth_password:
owasp_security_txt: |
  # Security.txt content

owasp_node_exporter_textfile_directory: /node-exporter-textfiles/
owasp_node_exporter_user_id: 65534
owasp_node_exporter_group_id: 65534
