---
galera_cluster_nodes_group: ""
galera_cluster_name: ""
privacyidea_variant: ""
project: ""
stage: ""

privacyidea_mariadb_root_password: ""
privacyidea_mariadb_name: ""
privacyidea_mariadb_user: ""
privacyidea_db_user_password: ""
