clamav_image: ""  
clamav_container_name: "clamav-scan" 
clamav_scan_directory: ""
clamav_log_path: "/var/log/clamav"
clamav_enable_auto_scan: false
clamav_scan_exclude_directories:
  - "/dev/*"
  - "/proc/*"
  - "/sys/*"
  - "/run/*"
  - "/tmp/*"
  - "/mnt/*"
  - "/media/*"
  - "/lost+found/*"
  - "/var/lib/docker/*"  
  - "/var/lib/containerd/*"  
  - "/var/lib/nginx/*"  
  - "/var/lib/systemd/*" 
  - "/var/lib/snapd/*"  
  - "/var/lib/fail2ban/*"  
  - "/var/lib/private/*"  
  - "/var/lib/ubuntu-release-upgrader/*"  
  - "/var/lib/tpm/*"  
  - "/var/lib/update-manager/*"  
  - "/var/lib/usb_modeswitch/*" 
clamav_user_id: ""
clamav_group_id: ""
clamav_username: "" 
clamav_port: "3310" 
clamav_cron_hour: ""
clamav_memory_limit: ""        
clamav_memory_swap_limit: ""      
clamav_cpu_shares: ""            