clamav_image: "clamav/clamav:1.4.2"  
clamav_container_name: "clamav-scan" 
clamav_scan_directory: "/"
clamav_db_path: "/var/lib/clamav" 
clamav_quarantine_path: "/var/lib/clamav-quarantine" 
clamav_log_path: "/var/log/clamav"
clamav_enable_auto_scan: true 
clamav_scan_exclude_directories:
  - "/dev/*"
  - "/proc/*"
  - "/sys/*"
  - "/run/*"
  - "/tmp/*"
  - "/mnt/*"
  - "/media/*"
  - "/lost+found/*"
  - "/var/lib/docker/*"  
  - "/var/lib/containerd/*"  
  - "/var/lib/nginx/*"  
  - "/var/lib/systemd/*" 
  - "/var/lib/snapd/*"  
  - "/var/lib/fail2ban/*"  
  - "/var/lib/private/*"  
  - "/var/lib/ubuntu-release-upgrader/*"  
  - "/var/lib/tpm/*"  
  - "/var/lib/update-manager/*"  
  - "/var/lib/usb_modeswitch/*" 