clamav_image: "clamav/clamav:1.4.2"  
clamav_container_name: "clamav-scan" 
clamav_freshclam_container_name: "clamav-freshclam"

clamav_scan_directory: "/" 
clamav_db_path: "/var/lib/clamav"  # default is /var/lib/clamav
clamav_quarantine_path: "/var/lib/clamav-quarantine" 
clamav_scan_log: "/var/log/clamav_scan.log" 

clamav_enable_auto_scan: true 
clamav_cron_schedule: "0 23 * * *" 

clamav_scan_exclude_directories:
  - "/dev/*"
  - "/proc/*"
  - "/sys/*"
  - "/run/*"
  - "/tmp/*"
  - "/mnt/*"
  - "/media/*"
  - "/lost+found/*"
  - "/var/lib/docker/*"  
  - "/var/lib/containerd/*"  
  - "/var/lib/nginx/*"  
  - "/var/lib/systemd/*" 
  - "/var/lib/snapd/*"  
  - "/var/lib/fail2ban/*"  
  - "/var/lib/private/*"  
  - "/var/lib/ubuntu-release-upgrader/*"  
  - "/var/lib/tpm/*"  
  - "/var/lib/update-manager/*"  
  - "/var/lib/usb_modeswitch/*" 

clamav_scan_options: "-r --move=/var/lib/clamav-quarantine"