clamav_image: "clamav/clamav"  
clamav_container_name: "clamav-scan"
clamav_scan_directory: ""
clamav_log_path: "/var/log/clamav"
clamav_socket_path: "/run/clamav"
clamav_config_path: "/etc/clamav"
clamav_db_path: "/var/lib/clamav" 
clamav_folder: /clamav
clamav_folder_owner: 0
clamav_folder_group: 0
clamav_enable_auto_scan: false
clamav_scan_exclude_directories:
  - "/dev/*"
  - "/proc/*"
  - "/sys/*"
  - "/run/*"
  - "/tmp/*"
  - "/mnt/*"
  - "/media/*"
  - "/lost+found/*"
  - "/var/lib/docker/*"  
  - "/var/lib/containerd/*"  
  - "/var/lib/nginx/*"  
  - "/var/lib/systemd/*" 
  - "/var/lib/snapd/*"  
  - "/var/lib/fail2ban/*"  
  - "/var/lib/private/*"  
  - "/var/lib/ubuntu-release-upgrader/*"  
  - "/var/lib/tpm/*"  
  - "/var/lib/update-manager/*"  
  - "/var/lib/usb_modeswitch/*" 
clamav_user_id: "2330"
clamav_group_id: "2330"
clamav_username: "clamav"
clamav_docker_group: "docker"
clamav_port: "3310" 
clamav_cron_hour: "22"
clamav_cron_minute: "0"
clamav_resources:
  limits:
    cpus: '0.5'
    memory: '2G'
  reservations:
    cpus: '0.05'
    memory: '500M'
clamav_remove: false
clamav_quarantine: true
clamav_quarantine_path: "/var/lib/clamav-quarantine"

clamav_delete_old_container: false