---
    - name: Install packages
      apt:
        name:
          - libspeex1
          - libspeexdsp1
          - libodbc2
          - libtiff5
          - libpq5
          - liblua5.1-0
          - libsndfile1
          - libavformat58
          - libldns3
          - libswscale5
          - libshout3
          - python3-lxml
        update_cache: true

    - name: Create freeswitch group
      group:
        name: freeswitch

    - name: Create freeswitch user
      user:
        name: freeswitch
        system: true
        home: /usr/local/freeswitch
        comment: FreeSWITCH open source softswitch
        groups: freeswitch
        append: true

    - name: Download freeswitch binaries
      get_url:
        url: "{{ freeswitch_binaries_download_url }}"
        dest: /usr/local/freeswitch.tar.gz
        checksum: "{{ freeswitch_binaries_checksum | default(omit) }}"
        headers: "{{ freeswitch_binaries_additional_headers | default(omit) }}"
      register: download
      notify: Restart freeswitch

    - name: Extract binary
      command:
        cmd: "tar -xzf /usr/local/freeswitch.tar.gz -C /usr/local/freeswitch"
      when: download.changed

    - name: Set freeswitch user ownerships
      file:
        path: "{{ item.path }}"
        owner: freeswitch
        group: freeswitch
        mode: "{{ item.mode }}"
        recurse: true
      loop:
        - {path: /usr/local/freeswitch/, mode: ug=rwX,o=}
        - {path: /usr/local/freeswitch/bin/*, mode: u=rwx,g=rx}
      when: download.changed

    - name: Set freeswitch capabilities
      capabilities:
        capability: cap_net_bind_service,cap_sys_nice=+ep
        path: /usr/local/freeswitch/bin/freeswitch

    - name: Enable Freeswitch modules
      xml:
        path: "/usr/local/freeswitch/conf/autoload_configs/modules.conf.xml"
        xpath: /configuration/modules/load[@module="{{ item | split('/') | last }}"]
      loop: "{{ freeswitch_enabled_modules }}"
      notify: Restart freeswitch

    - name: Disable Freeswitch signalwire module
      xml:
        path: "/usr/local/freeswitch/conf/autoload_configs/modules.conf.xml"
        xpath: /configuration/modules/load[@module="{{ item | split('/') | last }}"]
        state: absent
      loop: "{{ freeswitch_disabled_modules }}"
      notify: Restart freeswitch

    - name: Create freeswitch systemd file
      copy:
        src: freeswitch.service
        dest: /etc/systemd/system/freeswitch.service
      register: freeswitch_systemd
      notify: Restart freeswitch

    - name: Systemctl daemon reload
      systemd:
        daemon_reload: true
      when: freeswitch_systemd.changed

    - name: Enable Freeswitch
      systemd:
        name: freeswitch
        enabled: true
