---
privacyidea_mariadb_root_password: "" 
privacyidea_db_user_password: ""
privacyidea_mariadb_packages:
  - python3-mysqldb
  - mariadb-server
  - mariadb-client
privacyidea_version: "3.8.1"
privacyidea_admin_password: ""
# privacyidea_enable_mariadb_setup: Controls the installation and configuration of MariaDB directly on this VM. 
# Set to true to enable setup, false if using an external MariaDB instance.
privacyidea_enable_mariadb_setup: false
