---
basic_fail2ban_jail_default: |
  [DEFAULT]
  ignoreip = 127.0.0.1/8 ::1
basic_fail2ban_jail_default_path: /etc/fail2ban/jail.d/default_jail.local
basic_fail2ban_jail_sshd: |
  [sshd]
  enabled = true
  port = ssh
  logpath = %(sshd_log)s
  maxretry = 3
  bantime = 3600
basic_fail2ban_jail_sshd_path: /etc/fail2ban/jail.d/sshd_jail.local
basic_install_python: true
