---
- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    api_version: v1
    name: monitoring
    kind: Namespace

- name: Add metrics-server chart repo
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: "https://kubernetes-sigs.github.io/metrics-server/"
  check_mode: false
  changed_when: false

- name: Install Metrics Server
  kubernetes.core.helm:
    name: metrics-server
    chart_ref: metrics-server/metrics-server
    update_repo_cache: true
    wait: true
    chart_version: "{{ metrics_server_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: kube-system
    values:
      "{{ metrics_server_values }}"

- name: Create vminsert-credentials secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: onepassword.com/v1
      kind: OnePasswordItem
      metadata:
        name: vminsert-credentials
        namespace: monitoring
      spec:
        itemPath: "vaults/{{ vault }}/items/victoriametrics"

- name: Deploy Configmap for Loki load test
  kubernetes.core.k8s:
    state: "{{ 'present' if loki_load_test.enabled else 'absent' }}"
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: loki-load-test
        namespace: default
      data:
        sample.log: "{{ lookup('file', 'loki-load-test-sample.log') }}"
        ocp-logtest.py: "{{ lookup('file', 'ocp-logtest.py') }}"
  tags: loki-load-test
  when: loki_load_tests_enabled

- name: Deploy Loki load test
  kubernetes.core.k8s:
    state: "{{ 'present' if loki_load_test.enabled else 'absent' }}"
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    template: loki-load-test.yml.j2
  tags: loki-load-test
  when: loki_load_tests_enabled
