---
- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    api_version: v1
    name: monitoring
    kind: Namespace

- name: Create Image pull secret token
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ image_pull_secrets_name }}"
        namespace: monitoring
      data:
        .dockerconfigjson: "{{ image_pull_token_secret }}"

- name: Add metrics-server chart repo
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: "https://kubernetes-sigs.github.io/metrics-server/"
  check_mode: false
  changed_when: false

- name: Install Metrics Server
  kubernetes.core.helm:
    name: metrics-server
    chart_ref: metrics-server/metrics-server
    update_repo_cache: true
    wait: true
    chart_version: "{{ metrics_server_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: kube-system
    values:
      "{{ metrics_server_values }}"

- name: Create vminsert-credentials secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: onepassword.com/v1
      kind: OnePasswordItem
      metadata:
        name: vminsert-credentials
        namespace: monitoring
      spec:
        itemPath: "vaults/{{ vault }}/items/victoriametrics"
