---
- name: Install fail2ban
  apt:
    name: ['fail2ban']
    state: present

- name: Enable fail2ban
  service:
    name: fail2ban
    enabled: true
    state: started

- name: Create filter file for fail2ban
  copy:
    content: "{{ coturn_fail2ban_filter }}"
    dest: "{{ coturn_fail2ban_filter_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Fail2ban

- name: Create coturn jail file for fail2ban
  copy:
    content: "{{ coturn_fail2ban_jail }}"
    dest: "{{ coturn_fail2ban_jail_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Fail2ban
