---
- name: UFW
  import_tasks: ufw.yml


- name: Install python3-pip
  apt:
    name: python3-pip

- name: Install correct urrlib3 version
  pip:
    name: urllib3==1.26.15

- name: Coturn
  import_tasks: coturn.yml

- name: Fail2ban
  import_tasks: fail2ban.yml
