    - name: Generate SSH public keys list for SSHD Users
      set_fact:
        sshd_public_keys: "{{ sshd_public_keys | default({}) | combine({item.name: lookup('file', 'sshkeys/' + item.name + '.pub')}) }}"
      when: item.permissions.sshd is defined and inventory_hostname in (lookup('inventory_hostnames', item.permissions.sshd.hosts) | default('', true)).split(',')
      loop: "{{ present_users }}"
      tags:
        - sshd

    - name: Create {{ sshd_namespace }} namespace
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        api_version: v1
        name: "{{ sshd_namespace }}"
        kind: Namespace
      tags:
        - sshd

    - name: Deploy SSHD host keys secret
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        apply: true
        definition:
          apiVersion: onepassword.com/v1
          kind: OnePasswordItem
          metadata:
            name: sshd-host-keys
            namespace: "{{ sshd_namespace }}"
          spec:
            itemPath: "vaults/{{ vault }}/items/sshd-host-keys"
      tags:
        - sshd

    - name: Create docker token secret
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: docker-token
            namespace: "{{ sshd_namespace }}"
          data:
            .dockerconfigjson: "{{ image_pull_token_secret }}"
      when: image_pull_token_enabled
      tags: sshd

    - name: Add dbildungsplattform chart repo
      kubernetes.core.helm_repository:
        name: dbildungsplattform
        repo_url: https://dbildungsplattform.github.io/helm-charts-registry/
      check_mode: false
      changed_when: false
      tags: sshd

    - name: Deploy latest version of SSHD chart to update user keys on Cluster
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig }}"
        name: "{{ sshd_chart }}"
        chart_ref: "dbildungsplattform/{{ sshd_chart }}"
        update_repo_cache: yes
        chart_version: "{{ sshd_chart_version }}"
        release_namespace: "{{ sshd_namespace }}"
        values: "{{ sshd_values }}"
        wait: true
      tags:
        - sshd