---
- name: Restart Fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Restart Scalelite
  community.docker.docker_container:
    name: scalelite-api
    restart: true

- name: Restart scalelite-nginx
  community.docker.docker_container:
    name: scalelite-nginx
    restart: true

- name: Restart bbb-autoscaler
  community.docker.docker_container:
    name: bbb-autoscaler
    restart: true

- name: Restart OWASP
  community.docker.docker_container:
    name: scalelite-nginx
    restart: true

- name: Restart Redis
  community.docker.docker_container:
    name: {{ item }}
    restart: true
  loop:
    - redis
    - redis-greenlight
    
- name: Restart Redis Instaces
  community.docker.docker_container:
    name: redis-{{ item.name }}
    restart: true
  loop: "{{ scalelite_greenlight_extra_instances }}"
  
  