---
name: Trigger AWX on push to master

on:
  push:
    branches:
      - master
    paths:
      - plugins/**
      - roles/**

permissions: {}

concurrency:
  group: infra-schulcloud-master

jobs:
  trigger_awx:
    uses: hpi-schul-cloud/infra-tools/.github/workflows/trigger-awx.yaml@master
    with:
      job_id: 33
    secrets:
      AWX_TOKEN: ${{ secrets.AWX_TOKEN }}
